apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudnative-pg
resources:
  - ./namespace.yaml

helmCharts:
  - name: cloudnative-pg-chart
    repo: oci://ghcr.io/alexander-zimmermann/charts
    releaseName: cloudnative-pg
    version: 0.27.1
    valuesFile: values.yaml
    namespace: cloudnative-pg

labels:
  - includeSelectors: false
    pairs:
      homelab.app: cloudnative-pg

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  argocd.argoproj.io/compare-options: ServerSideDiff=true
  argocd.argoproj.io/sync-options: ServerSideApply=true
