imagePullSecrets:
  # Secret used by Kubernetes to authenticate when pulling the operator image.
  - name: dhi-registry-secret

resources:
  # Container resources for the CloudNativePG operator Deployment.
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
