cluster:
  extraManifests:
    - "https://raw.githubusercontent.com/alexander-zimmermann/homelab/bootstrap/dist/dev/cilium.yaml"
    - "https://raw.githubusercontent.com/alexander-zimmermann/homelab/bootstrap/dist/dev/argocd.yaml"
