---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`hubble.zimmermann.phd`)
    target:
      kind: IngressRoute
      name: hubble

  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: hubble.zimmermann.phd
    target:
      kind: Certificate
      name: hubble-tls-cert

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: cilium-operator
