apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Ingress Host Patch
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`grafana.zimmermann.phd`)
    target:
      kind: IngressRoute
      name: grafana
      namespace: grafana

  # Certificate DNS Patch
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: grafana.zimmermann.phd
    target:
      kind: Certificate
      name: grafana-tls-cert
      namespace: grafana

  # Scale Down Patch
  - patch: |-
      - op: replace
        path: /spec/deployment/replicas
        value: 1
    target:
      kind: Grafana
      name: grafana
      namespace: grafana

  # Service Patch - Dynamic LoadBalancer
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/labels/bgp.cilium.io~1ip-pool
        value: default
      - op: add
        path: /metadata/labels/bgp.cilium.io~1advertise-service
        value: default
    target:
      kind: Service
      name: grafana
