apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject domain name into the Certificate and IngressRoute
  - sourceValue: grafana.zimmermann.phd
    targets:
      - select:
          kind: Certificate
          name: grafana-tls-cert
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: grafana
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1

patches:
  # Configure resources for Grafana Instance containers (main container & dashboard/datasource sidecars)
  - target:
      kind: Deployment
      name: grafana
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: grafana-sc-dashboard
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 25m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

      - op: test
        path: /spec/template/spec/containers/1/name
        value: grafana-sc-datasources
      - op: add
        path: /spec/template/spec/containers/1/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi

      - op: test
        path: /spec/template/spec/containers/2/name
        value: grafana
      - op: add
        path: /spec/template/spec/containers/2/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi

  # Configure resources for Grafana Image Renderer
  - target:
      kind: Deployment
      name: grafana-image-renderer
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: grafana-image-renderer
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
