---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cilium
resources:
  - ./certificate.yaml
  - ./ingressroute.yaml
  - ./bgp-cluster-config.yaml
  - ./bgp-peer-config.yaml
  - ./bgp-peer-password.yaml
  - ./bgp-advertise-lb-services.yaml
  - ./bgp-ip-pool.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
