apiVersion: apps/v1
kind: Deployment

metadata:
  name: smtprelay
  namespace: smtprelay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtprelay
  template:
    metadata:
      labels:
        app: smtprelay
    spec:
      containers:
        - name: smtprelay
          image: grafana/smtprelay:latest
          args:
            - "-config=/etc/smtprelay/config/smtprelay.ini"
          env:
            - name: OTEL_SDK_DISABLED
              value: "true"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/smtprelay/config
            - name: secret-volume
              mountPath: /etc/smtprelay/secrets
              readOnly: true
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 2525
              name: smtp
      volumes:
        - name: config-volume
          configMap:
            name: smtprelay-config
        - name: secret-volume
          secret:
            secretName: smtprelay-icloud-credentials
