apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smtprelay
resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./sealed-secret.yaml

configMapGenerator:
  - name: smtprelay-config
    files:
      - smtprelay.ini

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: smtprelay

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
