apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: smtprelay-icloud-credentials
  namespace: smtprelay
spec:
  encryptedData:
    secrets.ini: AgBcWMoXDYjsuDjNzy26x5Bo1eotQ7+hxabmm2U0XSm1OrnGVZcb+vvMCXirD1dZo6Cihf+JRkAQ1K3MV0GqNnalHLzaYxyVNHxsmaUi8K1pDbmEqprkRzrYxhoO6CRim5qG0HkyzdlD79lvUGukM7oLWJGzqVCa7l1n036z1i9KP2fQOQrXLbwSuVMjYHpc2BT1MSdbQ15cndFdo1vL8xxoIn+2Wmeq2TwvD8Z4LzNQVdB0F3LwCSiGGug/LRj/fu/jVoWS5w5OWXs+QrziGbN6GhNV/FPUO9Q7JmMDI9ssoBKGVRpUy0k3tX4pZO3mGqs4Zbwn95xEhIvi3H432LC788XCjS4V67wdIlCf9cWZN8tvVvTgRHS5Y7Muv5htzQFC8auFLZvUbkbys/CH+Iw/pXsFc1OohNhN/3GrybWWhADfegsmB/gLXVc4803JQiKAREB5qDr7h3oNWDLvfkeuMMxT7q2DHPiPVbSeS+QoKX7cmFjR2Ccf23yIpyQ4UOVtqxu5Z/B3+Sw1fhQSph+itfcpeoAaiVUgrjlC+pklOvWlaZgimoY97GCTxaI9Jk3/ROgjpwJ8Fqum2wpepHv9xBLc1OSFyWUdpn9wknJd/pzkUlqnxNk7YXBEUxHCtVTcdK7ARmylWBRRZUcErmWvhyQERfdbvUg5CHxnZbeToOE/ghkbTm5w61SJEnj5c/cUUnQ63JrHnXdaDn+gKGOwUzbkW4+zM4r1IjThaSyxvd18YPCynOXPZ0wkRohhzWR+J/dbeIBrOL7H6sohKuFFEE2yLJ1mBK5Q6Q==
  template:
    metadata:
      name: smtprelay-icloud-credentials
      namespace: smtprelay
    type: Opaque
