apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: smtprelay-icloud-credentials
  namespace: smtprelay
spec:
  encryptedData:
    secrets.ini: AgCrtjp/c7+ViMPUlFius4v7drBk5nYz6L69EOVOKwbeMO97mC0oy0XFjSOAZJ4Yij7UD2uThP+jMyCTKaZNB4FqrvffczPUwAEO2XcC7VuqdkE7qMknjadyh6hILho9CZJFVZYexdlJfsLWqjklSZGB+NHbB2JJqHwLOpZOes2Ytotzr3G1kUOXATFQMD9/i7Rtnod+alN5gHQy4nJEboblk10Drxhu9+23dPLGf4UeO+rBvwtVnRLWr/zlagn/J5MBdrtK5jY+fURblLbbob77uZztUnInHlu5lbNqWdrpTJG2QFwq+bLNeArOJDRauZUSMd4T2PrjZWWM+grUdt8Cal3PdCKWZ4/NCdV9vJxfbQIUU39xBFcz+aaoFqk/fOTzZiu+SjGYP9cR50oV3RvwKMsyvpejhMwnaFYuS5/K5WBq7KnPNhJTDFFH05P1Qm09KQ6Y6YCmrn3PBhkrKxoRgQN2w6yJVW6wSr9gFSv1fs5hDQTlKu4/1dl2kXBBnptTNWzbFrc2Ts1hzKdGCxwk9/KWfmVkkJOtcjan7qyaneTl0OTqyBg1SMUI1CB+qKD0xzuOWSM7qLfFy+XAHH2IfPziBam079zc4Sp5iXz9AEgOXrI4aTdj5ROznF2XzreQqjId1YSHlir4N877GRu9VyWtBYaoXsTjI1sxUj6TSSyJjbFWA551hPDMVWOish9Y+IDL9uqQnvT2IKZlzSie1DUPsVNivkOsxECnWKjG4nAb/0H13dHSha81i3bFChXvxv20kACQvTMuElVmDnz3ln3zH32bZD7CGA==
  template:
    metadata:
      name: smtprelay-icloud-credentials
      namespace: smtprelay
    type: Opaque
