---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtprelay-icloud-credentials
  namespace: smtprelay
spec:
  encryptedData:
    secrets.ini: AgBqjxh6g0UBPwbULoGtnDshppXGdCJmO2rdonFFyq9YXYNTYGiCg1yuZYLtS8wo9K2tKNDDzrCyYQpY4n88CS1Sd7uSHFgQ6sXgtZa4933GUutRGJbdiNKp3TK2lHVx67FhjgLN/v0C0SnYFyEEpoRGRfY455hwcZ0a26WuiPR9BwYsY71AF9DLlTfqK+yy7LTVvkYxR/8XMkhtjABlaPFhxyljUYEmcT3Nn+eLPE0LQTye8a20e9iX+m1moI0bhNPsr7wbkvgTE094y2vAMjitVnH9K4Iksqsjs4nbxEFpEuvlRiPDkAsm8WoAclhaKMfYHbv0RPkJ/jt+i3Ke0HpCKOqMYA//ysZds/SYEF6pNSLiiu4NTQd1mtOF20eAgiUkLE17jzB2IfFoaHP4DWbCLN3fS0WcWLOLqU58cfE4gUC25DdW6MC3gJpHkk+KV85jpw5sfU7HA/BmbWwm/xZyikZrd8MWHNphrzZ5hMUzJ2aji9NSpny6o6BRAKn3Mn65ecxe2y4eqPq6zdBKUBqUJl+fjdsSj//5zL7FdfqqGlDO6micIztYciUPGzcDSpmtD7iUqmr75dWcOwAMsK20jxNBnhXOJGm2GCORWYSAO7CexRMlpjlbR6xsWW8rT5xJA+R7AQLygPAUToXfjAFyE1BtrBjbgTgAIe5giEz2UR85dcTMYHEtuladvsy6n3w2IHlJ/x98esBuNbhXlPmrMXkTgDQkq/J6hGExtvGd+gxv6JhI0iWhMa+JI0j3QPuPYp+CAqucJxk4HVbmxCObxMpWSZy4kUPbRA==
  template:
    metadata:
      name: smtprelay-icloud-credentials
      namespace: smtprelay
    type: Opaque
