apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: smtprelay-secrets
  namespace: smtprelay
spec:
  encryptedData:
    REMOTE_PASS: AgCz/FF1OLHT3Ajo3wFr6VlhblSm8TmMguwJnCy7xDTz9EoCkjFByFHz/R33NKBPbfdXEH7Z8a0FfqURhbMe4EkweBUQht6FzSWB7s6hL+x0v1LVJGoCsgOIpTlWpct6voCiG/47m0ag1TTCM9EF9Faqz2H8TQ1mKijSRgBgiw9k4kNLd2DrrGLYeSbWSnV809ECO6jxOb0g8kzqQyTTap+Fnhg6/MuhqbOjIQ4bTHxs6qIqIS+lfBv8X0Bx490p+RbkAKLUw38lT1gJpc+AESA0EGIix1+XlxnbUcN+JoeH2SbI8Sc1kRhkEkD+sd0eg2L2QcGhZepCI2agMBcwNq/ipjXDZR1OZd4WAhipxqUypHl2uejgCFdHdzUp9klJgm7MHdoacRfCSJEV0O8dMOCmFoUvJSZvc3FszODTnJAe9w34swMIXgroQbhQpCPVy+QXvCMzvP8ZkNf91uW9kxW3ErkiYNg6VU6d4o9gVehCjDxVxvBEWr9AMubhHXc67/7KQm4vIUUlKK0EqC4pmD90fGHUdz3VPIfBua/OqULdMuKmEafmiFDcUn9ZIEHdmCa55sCDyfqwXoKvi/sL0J6nZYMuTMQbETwlCM4r8TJA9CExW3Lmiw8RK3kdHyLZ9MUkf8l+yojFmpxf/vYAbigVzDDK+fFUIvZCV4dtOVKgJeak6oF8pwNrJsZ0a/OEQ6RCqcMaRBV2ck2Ia+GMq2uD+y2i
    REMOTE_USER: AgBXGQa8RxM1cuHPMmjoJdILMjdhUTO06LoxXqt5zt3b7BDTsiilgkgl5tAVp3LyfNJYIcEtQuAAY9RPIVN1QUQeCiF5Loj0aNNO06xMgiMlSrytNlG25eFiOnmRPdYY6eu79LZ9QZ5Q+7m0qSdr+wIVuI7+IK8xbbAqGZnZyPNsc8hhKoY88eU8Drd44CdljX+2ebwAQUHmwC90se3pnBZ0uOacFGl/ZhnR64GkXNSvhgCuQc7YT/N8FhgnuZUbhfsAJZIGu2o5aDX0p/thXV4kAs9g22N6tbGa3WlJWkA5dIiXl0FhCBoyrhBKstINwQ20m2ViNAFKhBWqqV1QG7lSfSnaUGD6/vjgjX2bzjEP33xw1HNgQlXvX7aitvRhLnDS6KQX6IXg0rLnfO2p7Wis9WyXDNZHDWcN4+RRhCQ11sxZzgLyrqOv+FQY/CcGwFg7d4AltlhymQbBqr8y2dzh4uosSatrYg67GLdtx6DuBC+sEnyh/xboUJWNxgi/q2BsE+0hXCvn2i7fqwoj2gF1+CPbG+tUqPmKi1lqaJaaF5YPI68fl2O0nvDn2VCohCOH7359JOhZCyLt2SPANzM+I3Q8Z6jF4PvoPkHHk0ifTj3MCK+EKMjiHiR49TGXoVFjdRKIT6nYOOAlf0HPS87hI1Oa08SlCvcNURB8C+QIhAkMc2kolv69wXEOtzqAw/eEoGWOXpg8mjiQUtcNsbnFSVNS1OG9X1Jv
  template:
    metadata:
      name: smtprelay-secrets
      namespace: smtprelay
    type: Opaque
