---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtprelay-icloud-credentials
  namespace: default
spec:
  encryptedData:
    secrets.ini: AgCsj+dl40UefSL/ZyqXdim433Du/Y++2vqW+CQDC30KZqGQsAtaQCQ8SJjK0MVDGPPOitvRU0GhmUzbsOxmRNgYjGM27v7LFh2MBHV0ZIxxO5b6zOfIhiBETO438mOxF4B/IjSDebq4KmdihDmy2tOfJteOgBtPOXSBAdzq9QkGDhjs0M8tCwFIUaNW8xki4ZqB97WW5Tj3AqamarjtAgNm6XjGfeyj8M4w/84ycxpUhSe9I/nDcduYfohezmJ2WXV+WfFe5q6mbufr4qfDUGvYiEZyF48+5iTCZUlGxEiEmU3qG8Ry/LBz+9LIw0uDZX06hJSltOeInvwjAqqsNMX5Wq+WHtfX2k5hPriuJreMWYukfuRGdtwWcE95se1ZbIjevWbNNrv4OFv0oYDI+CAMlv4CtLzm8mWOdCIXKJmwDwEuS/M2RiuP4TtJymas6itdvj2mZLNgq8oyaq1aK97BxBnWWTwg8VpdwBuEu8IMBcMY+SMjjix/kBcL5/czATEvjJIh6YlSRCDa4JMvChDENRHixReAsoSe42+/4B4rzwVYDpuvnhHaOEX37OIZBSiiS/VzGGCDwfAZ/W1FnV5x/gbPyhK4ed7DaHUL37O9lySIwP+2cJAOBRrJZHNcQTmVlNyjdSkenVLS9CUtcZIY9/wjs8nBzQFzAz60M2IrmTcNcDXKLxSVZR2VOXl5/tiXZdHxepUNtLrPWQ/qIalSRVxMMyXPxSZxr2qA4r78m2GN44EQePGJFwk5SGhtuTtOvx1lmXTwwmzq82f6ZzKx7fXhAF4qhvPqsg==
  template:
    metadata:
      name: smtprelay-icloud-credentials
      namespace: default
