---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: smtprelay-secrets
  namespace: smtprelay
spec:
  encryptedData:
    REMOTE_PASS: AgBa4ftEG4uFOeo0sthOQuL+30OT0k5LhF6xy7ytTI5J4ARgMnKCioV2kSwkFhVdJom554u/mx7e/rZexfSvbvMsNaqZtoJw9FDOD5gkKHJKK4UtoaVqPv61z5GpgtGjm605YZ2YSiiL8/peNWCTBdMv9/q2pzVbdEcezy21tVumVd9bctYjTRWLZP5m+ZY92VkEZxdEZJVVXjKpe+/RI1YzOZXxfdZyU+khn0f/Mv+sCDsxHQf+Trl6I4aYClKrSl8bXg9clATW2TV8FPdROG3xszC6HiR0tdDxhZRXx/r+3ZG3cjcXDAAzt1c3zJqcPsamDAmV6LfbOtEWC+EN3fugRDp2rPchflVr1KHB/nSuo5jZTtCBIvMoFiCuH3ob8Dnv2fRvzk5Cu5Cs/foaKYl/n2NEXm1wXPT2dOBKyZI95puRlnTAi8MqWNNspQqMeB5NQ+L6UGesZrV1dLi0iD/07UO+dQ5TSwvNtHYctDPuSN7i4A5PoP9JxtwZdq/5vhu1iGQELS7Rt75y8FOC3q2RzLVXIKtcZcXP0Ng2TbyxmdSRie5psZkDcPRcD1mrqEErqheZx6JLjs4Yux44FKnmZt7ccRh02gzmo43vY2fA+oF8fszq+l6wgl+pv79Z9/miV2lqw2PiScDg17Gv8bwhOpwn4PcXYbpCSisd4lSMYhR+m76ciY8dxQ8klUay8zWZDL/64FRXgC5NP65uu41FgxLY
    REMOTE_USER: AgBpaQJnkL+Qk4/vK+gkca1h9hfu5Y9hYsgkbdHdkGHgoBOwNDXD5TQsG/DQ6Zw7aD4kcki/Z3F8OKDE5PufnhOmiKiYt8vgKA9z36FVGSGD7/949zN8+8oUuScp/2bGVOQctOpmuP91bkWcU+JLpl8BY4B+ciKVVLRizVYlPT4CAfDLTs/PI73wet+OR/Hb9EsLmpRDtDIVkn0eIYfzUN2fCKP04dBSXOnuACq+av0dvsWeS+WV8mSiXhg/Myg6WXANyLPF6GIlh/3y1x3FPB9hPlJywS11NBFhtcBwQKz2uZzfNHPy5r0b4+5lPim00G5zqVgk4kYUxeZQwz2/O/Kg1H2o8i6UEOFhGzx/M0hEhEZWN4L/ckKLspea+XeXPupKpAKl8zbmgWXYPT1+ApPVpSwcL2WLZxUDqUMnYXyro/qVUAb3unD2XJ8X0PFZnbhGpYWwI2JpORBTBM8S8kfYG1pj3jhdzsrE6DkTFcR4aeEtcfMNIgZ1iXf82Xdx1hTJ/hOi+6U6uqcpTV2cR6M+RJClr7f1QzgLq/muf5zjXwRtbX8tLWeyQ5kCPvP8iGwjzWUmW1K3PRhzgvL590eX1qZTbmTOkB3OfcxN0WGNtA+FUd4xe+rSjntvt8aK8rNkfnLv7+AVzMppMLcBkymbQCUva02kuc1MEtf5guXF6ZdiIMD4YSQUrlBd9GBa+K5ORCphi1e3YN9Y24MactzwCL6EwXY2Vd3h
  template:
    metadata:
      name: smtprelay-secrets
      namespace: smtprelay
    type: Opaque
