apiVersion: v1
kind: Service

metadata:
  name: smtprelay
  namespace: smtprelay
  labels:
    # Expose smtprelay service via Cilium/BGP-announced LoadBalancer
    bgp.cilium.io/ip-pool: default
    bgp.cilium.io/advertise-service: default
spec:
  selector:
    app.kubernetes.io/name: smtprelay
  type: LoadBalancer
  ports:
    - port: 25
      targetPort: 2525
      protocol: TCP
      name: smtp
