---
apiVersion: v1
kind: Service

metadata:
  name: smtprelay
  namespace: smtprelay
spec:
  ports:
    - port: 25
      targetPort: 2525
      protocol: TCP
      name: smtp
  selector:
    app: smtprelay
