apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crowdsec
resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml
  - ./database.yaml

helmCharts:
  - name: crowdsec
    repo: oci://ghcr.io/crowdsecurity/helm-charts
    releaseName: crowdsec
    version: 0.22.0
    valuesFile: values.yaml
    namespace: crowdsec
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1

labels:
  - includeSelectors: false
    pairs:
      homelab.app: crowdsec

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
