apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject domain name and path into the StorageClass
  - sourceValue: linux.zimmermann.eu.com
    targets:
      - select:
          kind: StorageClass
          name: nfs-csi
        fieldPaths:
          - parameters.server
  - sourceValue: /srv/k8s
    targets:
      - select:
          kind: StorageClass
          name: nfs-csi
        fieldPaths:
          - parameters.share
