apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # NFS share configuration
  - patch: |-
      - op: replace
        path: /parameters
        value:
          server: linux.zimmermann.eu.com
          share: /srv/k8s
    target:
      kind: StorageClass
      name: nfs-csi
