apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # NFS share configuration
  - patch: |-
      - op: replace
        path: /parameters
        value:
          server: linux.zimmermann.eu.com
          share: /srv/k8s
    target:
      kind: StorageClass
      name: nfs-csi

  # Scale down replicas - NFS controller
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: csi-nfs-controller

  # Scale down replicas - Snapshot controller
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: snapshot-controller
