apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  server: PLACEHOLDER
  share: PLACEHOLDER
mountOptions:
  - nfsvers=3
