---
ci_network_config:
  std_linux:
    dhcp4: true
    dhcp6: false
    accept_ra: true
    dns_search_domain: [zimmermann.eu.com]

  cluster-mgmt:
    dhcp4: true
    dhcp6: false
    accept_ra: true
    dns_search_domain: [zimmermann.eu.com]
