apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject domain name into the Certificate and IngressRoute
  - sourceValue: console.rustfs.zimmermann.phd
    targets:
      - select:
          kind: Certificate
          name: rustfs-console-tls
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: rustfs-console
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1

patches:
  # Reduced developer footprint for RustFS server
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
    target:
      kind: Deployment
      name: rustfs

  # Developer storage for RustFS data and logs
  - patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 512Mi
      - op: replace
        path: /spec/storageClassName
        value: longhorn
    target:
      kind: PersistentVolumeClaim
      name: rustfs-data
      namespace: rustfs

  - patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 128Mi
      - op: replace
        path: /spec/storageClassName
        value: longhorn
    target:
      kind: PersistentVolumeClaim
      name: rustfs-logs
      namespace: rustfs
