http:
  # Add router
  routers:
    ai-pro-3:
      rule: Host(`ai-pro-3.zimmermann.sh`)
      entryPoints: websecure
      tls:
        certresolver: cloudflare
      middlewares: chain-add-1FA-BSC@file
      service: ai-pro-3

  # Add service
  services:
    ai-pro-3:
      loadBalancer:
        servers:
          - url: https://ai-pro-3.zimmermann.eu.com
        serversTransport: ai-pro-3

  # Configure transport between Traefik and http server
  serversTransports:
    ai-pro-3:
      insecureSkipVerify: true
