http:
  # Add router
  routers:
    proxmox:
      rule: Host(`proxmox.zimmermann.sh`)
      entryPoints: websecure
      tls:
        certresolver: cloudflare
      middlewares: chain-add-1FA-MFA_PWD-proxmox@file
      service: proxmox

  # Add service
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: https://proxmox.zimmermann.eu.com:8006
