http:
  # Add router
  routers:
    warp:
      rule: Host(`warp.zimmermann.sh`)
      entryPoints: websecure
      tls:
        certresolver: cloudflare
      middlewares: chain-add-1FA-MFA_BSC@file
      service: warp

  # Add service
  services:
    warp:
      loadBalancer:
        servers:
          - url: http://warp.zimmermann.eu.com
