http:
  # Add router
  routers:
    dali1:
      rule: Host(`dali-1.zimmermann.sh`)
      entryPoints: websecure
      tls:
        certresolver: cloudflare
      middlewares: chain-add-1FA-MFA_PWD@file
      service: dali1

  # Add service
  services:
    dali1:
      loadBalancer:
        servers:
          - url: https://dali-1.zimmermann.eu.com
        serversTransport: dali1

  # Configure transport between Traefik and http server
  serversTransports:
    dali1:
      insecureSkipVerify: true
