http:
  # Add router
  routers:
    verso:
      rule: Host(`verso.zimmermann.sh`)
      entryPoints: websecure
      tls:
        certresolver: cloudflare
      middlewares: chain-add-1FA-MFA_PWD@file
      service: verso

  # Add service
  services:
    verso:
      loadBalancer:
        servers:
          - url: https://verso.zimmermann.eu.com
        serversTransport: verso

  # Configure transport between Traefik and http server
  serversTransports:
    verso:
      insecureSkipVerify: true
