http:
  middlewares:
    chain-add-0FA:
      chain:
        # Std. middleware w/o any additional authentication
        middlewares:
          - cloudflare
          - crowdsec
          - rate-limit
          - secure-headers
          - remove-headers
