http:
  middlewares:
    chain-add-1FA-MFA_BSC:
      chain:
        # Std. middleware w/ additional MFA for basic authentication
        middlewares:
          - cloudflare
          - crowdsec
          - rate-limit
          - secure-headers
          - authelia-BSC
          - remove-headers
