http:
  middlewares:
    # Middleware for all standard services
    secure-headers:
      headers:
        frameDeny: true
        stsSeconds: 15552000
        stsIncludeSubdomains: true
        stsPreload: true
        accessControlAllowHeaders: '*'
        accessControlMaxAge: 100
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        addVaryheader: true
        hostsProxyHeaders: 'X-Forwarded-Host'
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: 'same-origin'
        permissionsPolicy: 'accelerometer=(), autoplay=(self), camera=(), encrypted-media=(), fullscreen=(), geolocation=(self), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(self), usb=()'
        contentSecurityPolicy: >
          default-src 'self' *.zimmermann.sh;
          script-src 'self' 'unsafe-inline' 'unsafe-eval' traefik.github.io static.cloudflareinsights.com ajax.cloudflare.com www.gstatic.com;
          img-src 'self' grafana.com data:;
          style-src 'self' 'unsafe-inline' www.gstatic.com blob:;
          font-src 'self' data:;
          object-src 'none';
          connect-src 'self' cloudflareinsights.com grafana.com
          worker-src 'self' blob:
        customResponseHeaders:
          X-Robots-Tag: 'none,noarchive,nosnippet,notranslate,noimageindex'
          server: ''

    # Middleware only for Proxmox
    secure-headers-proxmox:
      headers:
        frameDeny: false
        stsSeconds: 15552000
        stsIncludeSubdomains: true
        stsPreload: true
        accessControlAllowHeaders: '*'
        accessControlMaxAge: 100
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        addVaryheader: true
        hostsProxyHeaders: 'X-Forwarded-Host'
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: 'same-origin'
        permissionsPolicy: 'accelerometer=(), autoplay=(self), camera=(), encrypted-media=(), fullscreen=(), geolocation=(self), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(self), usb=()'
        contentSecurityPolicy: >
          default-src 'self' proxmox.zimmermann.sh;
          frame-ancestors https://proxmox.zimmermann.sh;
          script-src 'self' 'unsafe-inline' 'unsafe-eval' traefik.github.io static.cloudflareinsights.com ajax.cloudflare.com www.gstatic.com;
          img-src 'self' grafana.com data:;
          style-src 'self' 'unsafe-inline' www.gstatic.com blob:;
          font-src 'self' data:;
          object-src 'none';
          connect-src 'self' cloudflareinsights.com grafana.com
          worker-src 'self' blob:
        customResponseHeaders:
          X-Robots-Tag: 'none,noarchive,nosnippet,notranslate,noimageindex'
          server: ''
        customFrameOptionsValue: SAMEORIGIN
