apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # SMTPreplay service with static IP and BGP advertisement
  - target:
      kind: Service
      name: smtprelay
    patch: |-
      - op: add
        path: /metadata/annotations/io.cilium~1lb-ipam-ips
        value: "192.168.10.25"
