apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia
resources:
  - ./namespace.yaml
  - ./database.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: authelia

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
