apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: authentik-db
  namespace: authentik

spec:
  instances: 1

  # PostgreSQL version and configuration
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1

  # Apply I/O workload class "heavy" to the database pods
  inheritedMetadata:
    labels:
      homelab.app/io-class: "heavy"

  # Authentik DB is "heavy" I/O workload. Prefers not to be on the same node as "heavy" I/O workloads
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname
    additionalPodAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: homelab.app/io-class
                  operator: In
                  values:
                    - "heavy"
              namespaceSelector: {}
            topologyKey: kubernetes.io/hostname

  # Storage configuration
  storage:
    size: PLACEHOLDER

  # Bootstrap from scratch or restore from backup
  bootstrap:
    initdb:
      database: authentik
      owner: authentik

  postgresql:
    parameters:
      # Memory settings
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
      work_mem: "8MB"
      maintenance_work_mem: "128MB"
      autovacuum_work_mem: "128MB"

      # WAL settings
      wal_buffers: "16MB"
      max_wal_size: "1GB"
      min_wal_size: "80MB"
      wal_keep_size: "128MB"
      wal_compression: "on"

  backup:
    barmanObjectStore:
      serverName: PLACEHOLDER
      destinationPath: s3://authentik-backups
      endpointURL: http://rustfs-svc.rustfs.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: rustfs-admin-credentials
          key: RUSTFS_ACCESS_KEY
        secretAccessKey:
          name: rustfs-admin-credentials
          key: RUSTFS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup

metadata:
  name: authentik-db-daily
  namespace: authentik

spec:
  schedule: "0 0 2 * * *"
  immediate: false
  backupOwnerReference: cluster
  cluster:
    name: authentik-db

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authentik-db
  namespace: authentik
  # Prometheus Operator label (Opt-In)
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: authentik-db
  podMetricsEndpoints:
    - port: metrics
