apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik
resources:
  - ./namespace.yaml
  - ./database.yaml
  - ./ingress-route.yaml
  - ./certificate.yaml
  - ./sealed-secrets.yaml

helmCharts:
  - name: authentik
    repo: ghcr.io/goauthentik/helm-charts
    releaseName: authentik
    version: 2025.12.3
    valuesFile: values.yaml
    namespace: authentik
    includeCRDs: true

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: authentik

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
