apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik
resources:
  - ./namespace.yaml
  - ./database.yaml
  - ./ingress-route.yaml
  - ./certificate.yaml
  - ./sealed-secrets.yaml
  - ./bucket-job.yaml

helmCharts:
  - name: authentik
    repo: oci://ghcr.io/goauthentik/helm-charts
    releaseName: authentik
    version: 2025.12.3
    valuesFile: values.yaml
    namespace: authentik
    includeCRDs: true

patches:
  # Configure LoadBalancer with Cilium BGP advertisement
  - target:
      kind: Service
      name: authentik-server
    patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/labels/bgp.cilium.io~1ip-pool
        value: default
      - op: add
        path: /metadata/labels/bgp.cilium.io~1advertise-service
        value: default

labels:
  - includeSelectors: false
    pairs:
      homelab.app: authentik

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
