apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik
resources:
  - ./namespace.yaml
  - ./database.yaml
  - ./ingress-route.yaml
  - ./certificate.yaml
  - ./sealed-secrets.yaml
  - ./bucket-job.yaml

helmCharts:
  - name: authentik
    repo: oci://ghcr.io/goauthentik/helm-charts
    releaseName: authentik
    version: 2026.2.0
    valuesFile: values.yaml
    namespace: authentik
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1

labels:
  - includeSelectors: false
    pairs:
      homelab.app: authentik

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"
