apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgAQ3gavyNQsfRDgBLckIw52y3oJjtAmjEhi5Gi/w4+ckYdz1C5r4Kt4jdT+l3DO9GXgnrUEFonaExzcvT/uRxOKqqRpuVXI5ho4fZAXIcUOV1Ni6Rd2VrdpJ4O29PIwQyhuTRK7E/rvMaz68pLqw19EzJwpCpTXMz/elrWbHCuh7YtaVK+jS6AeJBsihrLO6YN9PTbi7GWymuRuEPwWzFelKLU2i1+J/t/zQNLzxDFrNTsAV7iwNqDZy6XnxXfqAHzrTAiltcCAFcytGVowkLyDbTIW96v7ERk0pNtjSJ3oRckKjDZKd4O6gSSEmocQU+gFDG1FwkCsZJSZe21b3rE5yi9DSKzjWJjsd+JK2zLA1Na9mC2FvbnSbOvNK+gCV7b2itkt5CqLTRiPIJIZGeX9jofC6MMqRkGdO+vwt3JSzO0NbjWN9fj2EjCTMNHax/iUW8EtnxD9bgR67yupXu/f6diFx/xdI/FXiZD42keBF3tSS7Q2xy8gEPuZchyNioQkFTq4THKzyC0R0p0Bljb8k2WcToovI+dd3dCS6FiU8m5BWNwsN/VDXmukzHX5Y35ON9rSdIHSukA6nDpCVOymr6T9v0wUm4tvCRcRASC52AkuG62ub/+dJ/K/nDFZctbiSUeyPAsSxD7Fifv/Hm5sWe9+yWL6mVGOQfywuTSiutdUm7L8qCzrwvwnHhLBf+i1BUV2i5maIjMSDlsH6HWBUxj+jEKQt1wAiYICmvirAO4v20LJBesAyzwq1T9dT2g=
    AUTHENTIK_SECRET_KEY: AgCnOG0U4G6uWwb5OxcXTeG3k4yRV4rgASTyf1zbuYiC9pVDQ73uF9hqp4kvCBZnTo4IyQktyH8G0lqeDXcKP9FVSNnnB36VmMJO7fU/xy8doNIDLXmpWuGkIJRisftFyssxRG6RqJtiZ/3CgKdaBJBE7J1m3O6N6/dbfcpWtk5uaDX0Z4eDLnz3SKEJcq83Qe3szKQTM4LzEHqSTFhl2xFexZQNqk8gwUq68l5ZDbR1yoHvoAkLc/n4TpvtIK7vCA6M7rSJrkIrZe1fF++nWkj1hMtSf81YtIseRf6PEreVbtJRPJpAvCZQtp+xlceKgfWSWnW0dchKkyPW/v3dde2Iko8irEC6H3kSCioq5VaFtFvjnpGajNA8NJlhkX1UBm5nxldvN9oFyrXs2m+YweADU9wNUj/UECjCOz+aqkVxekdXb/k4HsT7upKdUSFLyrV9vs9JYZKqHo/XJAim/IbAUGztgAHEHoOKObKSMY8ayhy1gS4XFpszRw9ZL3hglPMGZ/ryHJ0FwkapaMP1u38V+g2BcPt385R2iHXLtlNbCmzkPa2dBgF7J0nK/s8Sr5KEmglko18S4z+emjbofAFjFy7B9An/CzphsszQcGdF9D9y7taenhbiPUpttOgWMu0rgnKyBCEbO7tIRuF+ErnoX7tud8OlqkiR6NaaWB6p0CsKdMm/BrzZMvrcLtWGmarDY0ey4Wsv2Hup3EGoR3k+xjK+ir/2qeWsBJul21//LPK70O4r/n6m9ScFAqxEcaU=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque
