apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgAOR7xF4PIm807PQgprn7O7RsTGVYczh9Ogbr8y0g+TTKIlTBK6Y+GFGpRgDDXwp5+OLRKVy2tG+NObXQlsEe3XMqCsXISSZ4VEaI/jaQJgeTvgY4VXI62QX5sH6MxyaVb5TcIKda01ZjUZCXGze82IvziJ+5ReDSBAr2Uyu/uHpprxaSiDWUPy1EnNenUkYv4ZNoOJPVljpKL8vhb7VeUFQaVcHo17ztbDn0GE1Xfz+6cVY79yXjSskI/vbB3SzgUkOWc8NLOzcP1H17rSkDyfC7WbU+1v1pFEcvF5YUpcwsVqan+OuYgWmHx2fl7Q2JjgYaniSIUINOfRhG/zSFujDFUPR1HkOAcVor3YopjqL80yjXGUXHIkRvp5yPm8p0ocuz5qzdVQO8eCqDLkN+cPg/XzFx6zrBSh5+BLx6fEgbuwGAPXeMtG0r2yfvgdAu8q4QRhv5wWlP9mfCPZStxNJdsUDi9nCh/Ll6vSbQw/J4oAEMhxp0uKCK/5MLCaEXhJ5kCpmg2ixFP8nEl09nlRsyb5UjOayGqr1m/kQmFQzSDCtCahRcgiZaip1voDTw8AJpC7/6wvnILMEJmDjayEiQsZ2FQ8c1HcgYlJ3XtYHNCs9U7twbAGdQs9RgJFGWl+byOQ8GKJBImKKVhbtXS+xGV1S0wgw+NbxTHMy/hdh5X0cFUCxHCOAo7919Nf96jxZKM6zCUmp9DOJERO+boDnSN3Jorcljsofb4bX5XXrHbNO3p5lvTL1xwHXPy/p74=
    AUTHENTIK_SECRET_KEY: AgCathB3ZniX5nP4HZFvVY9KarjCLTkEJVKH6BV834lJYMQYaG3OHcjBjnUgWLTdsw1VZq77pky7Z6BPx1U8UABUhYwi2NhSz8fH5n+VIwog8vD9UbFj0VO+AJPAVxWQoYq7FHDj8fuXWYemws0IqS4edhbbY0UH5LzfHSB0cQwOyA9ihJIM42VApb1MA+j/lTU2uZHhNiqKv6oHnQsFKyg7VBVqvkmGUuoWhorBUt3SBe8HayYj8bhjHVZxM/ARGv6/hYvpX7+EcmxfUaVVwivGzl6vGRYqKx8XFdaQ6v0rV9cnaTdy0+KGg05KoLcxBKP3iVbEwPzGF7bKN+jHAJKfc/g4v/cxEjUrl1nNLgm4rClxmP88IbmuUOAJo1wmFCx0UHyDotFqBCGN+D7awryoKQEqUiboQgxV8MWwxna3vLy0OxreWqFtSIG+P7KBA9WdUlGJboc55BpRdBiK8fmCdYS7u76b45xTpCGqs2VwwWbjjzqR++y8htq5yF9zuBwKo2SBOl2PbVrtpFZN0U1kevylu8RqQkyPSUIQ+tRVNGNJ7QwS8Y1An5gm2V5gRc1jM/EurW3V+2eRIIt5IA913yLaP2ikD113/y/xN7jZ0lWKrjdiOIbfKcnxPZ2c30bLXWfRxATfwzJ+vINY7Zu63xk/fzUrl5ByhDyxlDcOP3zNhYoMSS82Dp694+4R1gBYm9zCX+nlZL+Z/nrKEJu0l+wLC7BVN+ILDd7OJkGFBaJSXcooqJnQvDoqrsSlCPY=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
    type: Opaque
