apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Ingress host
  # - patch: |-
  #     - op: replace
  #       path: /spec/routes/0/match
  #       value: Host(`alloy.zimmermann.phd`)
  #   target:
  #     kind: IngressRoute
  #     name: alloy-ui

  # Certificate DNS names
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: alloy.zimmermann.phd
    target:
      kind: Certificate
      name: alloy-ui-tls

  # Loadbalancer configuration
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/labels/bgp.cilium.io~1ip-pool
        value: default
      - op: add
        path: /metadata/labels/bgp.cilium.io~1advertise-service
        value: default
    target:
      kind: Service
      name: alloy-alloy-metrics
