---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./storageclass.yaml

helmCharts:
  - name: csi-driver-nfs
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    releaseName: csi-driver-nfs
    version: 4.12.1
    valuesFile: values.yaml
    includeCRDs: true
    namespace: csi-nfs-controller
