---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./certificate.yaml

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    releaseName: traefik
    version: 37.4.0
    valuesFile: values.yaml
    includeCRDs: true
    namespace: ingress-controller
