apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mimir
resources:
  - ./namespace.yaml
  - ./sealedsecret.yaml
  - ./job-setup-rustfs.yaml

helmCharts:
  - name: mimir-distributed
    repo: https://grafana.github.io/helm-charts
    releaseName: mimir
    version: 6.0.5
    valuesFile: values.yaml
    includeCRDs: true
    namespace: mimir

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: mimir

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
