apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: mimir-s3-token
  namespace: mimir
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAOTZM42kBJTGvN2qCjutr9aBEXC4qTEY9FLee9CvV+S0cyb9fDh3aOY3SrqeXTuQskDasJMDGyBAz4ZxHplDN2A/HVkVsoyZ4B17DoLXoXgdggLrGhEZ5lNBNTZbe7jf+Cd1TFQ7fOwn4B6Bj9q/JZQFpVK7XkWQ9g5meqc81CKZ3yK3NHRGdmrwXP5jWJXC37mh+7HKUwDVUR7Jf5cGNdG0KNLoCv+Pav9qvb5YoxFSuSxsxcQFUw/HL0Ke3V5ut8zFKZ0fb46vCjbBnWcjK/PJwR9s5xhL9x3wU+cvqlrK0cbcxaRs86sZrBY5Jsa4q90l+j84SWfzCtoNOFrWi7UOOSxe6FWlDQlaBLwRMhmDrMxwjlXEodDlgA8s54rNmoKHTx98D6W/cuICselzvFMzHui1BHFcArIzY0n5VaNQ5uFnX28bHCjRGsxITWCv6XyZkvJIkA7TMdWyEH+i2jwv4XnfNS15xmKadsSU3rUB7RyPqRb0d+12NmRetZxycPhWQPDsjkdhr3BBJfKKgYdZPGjiHHJpKa4VHTw60bFOLO2xZwSLB0HqrxGlK4YTQBj92xv49k/5f/5PQ/sT0gRyHv2ZhGmn20soAh9cNT+qNtURZLfVK6inOfNXi94p/+m9BH7pnWrQm++tpx+YKNBOXjzFP5rTGHOVUlvQLgnegJf8Jz6veMJB2JP1hJyW97S0qi3w==
    AWS_SECRET_ACCESS_KEY: AgBnp5rM+bmz2ysi30bK0HB9Er7ygsHhicGEwskfCpR8aMCdiplAFYXa+i4iRDOQVtsiJWq5gO2lX/vLgoKKcRa3x0ta72jrreNm3eblcHadUKWSWVyr5LubdiGFDJwBEGeihC8c20NafgnZtuj5sbJvvDQTUYMh89Fm97yfSLUG7kLckke8uAaliUK0aN6KPkF86IKmGLqy50sGY2vgcr/AtBoapcDhzXJnbYC38/EUI77URorqbTSefTQzB0JrBqvYMbrZN417iMylAxzAFlnlrApKVCPPz3w/xdT9TND33HYAAW7gfxXPPwAA0cpykjyIJMMMshO5J19LWHtmMmC0BLB4JkMjCSw2sDLRssqmqIqqpSjX0Idozr930bAGHUG2RYz+P63YHle0ZZjpl5Mc8iEc6/9pY4/lvE10aA7dqihHtybrmra05liMWpzN4GCmJO/UcH/Xy2/SNudFBLu5QMK4MBq31J9IZWfR/n7PdVRCmdJquPD6cTKFOk8JkYmCmXRFnwOfs8+JgwBWxksTmLGWnPPIi7xIFFWA396bLY0dJL/BBw9y+M9zlLNMZQxfJCk9xGpY7GNjWN10OIdBuTvxMC1iSkr9S4nugmM46wA5Usc/b/DPm2hNJH1awjki11jl9IgVXl1UCZLN8BwuiJPDnxd14jjlb/INMYUxs7g2zgQPwUqQ7BfeCSsSYCXkuSA2qfkJW7C9m9OSRZOtNQByRJgcGSqRugH/WvC6/8rn
  template:
    metadata:
      name: mimir-s3-token
      namespace: mimir
    type: Opaque
