apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: mqtt-tls-cert
  namespace: mosquitto
spec:
  secretName: mqtt-tls-cert
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - PLACEHOLDER
