apiVersion: apps/v1
kind: Deployment

metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1883
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-data
        - name: mosquitto-secret
          secret:
            secretName: mosquitto-secret
      containers:
        - name: mosquitto
          image: docker.io/library/eclipse-mosquitto:2.0.21
          # https://hub.docker.com/_/eclipse-mosquitto/tags
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Australia/Sydney"
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - name: "web"
              containerPort: 9001
            - name: "mqtt"
              containerPort: 1883
          readinessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 5
          volumeMounts:
            - name: mosquitto-config
              subPath: mosquitto.conf
              mountPath: "/mosquitto/config/mosquitto.conf"
            - name: mosquitto-data
              mountPath: "/mosquitto/data"
            - name: mosquitto-secret
              mountPath: "/run/secrets"
              readOnly: true
