apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mosquitto
resources:
  - ./namespace.yaml
  - ./persistentvolume.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./sealed-secret.yaml

configMapGenerator:
  - name: mosquitto-config
    files:
      - mosquitto.conf

patches:
  # Configure LoadBalancer with Cilium BGP advertisement
  - target:
      kind: Service
      name: mosquitto
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/labels/bgp.cilium.io~1ip-pool
        value: default
      - op: add
        path: /metadata/labels/bgp.cilium.io~1advertise-service
        value: default

labels:
  - includeSelectors: false
    pairs:
      homelab.app: mosquitto

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
