apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mosquitto
resources:
  - ./namespace.yaml
  - ./persistentvolume.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./sealed-secret.yaml

configMapGenerator:
  - name: mosquitto-config
    files:
      - mosquitto.conf

labels:
  - includeSelectors: false
    pairs:
      homelab.app: mosquitto

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
