apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mosquitto
resources:
  - ./namespace.yaml
  - ./persistentvolume.yaml
  - ./deployment.yaml
  - ./service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: mosquitto

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
