---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana
resources:
  - ./namespace.yaml
  - ./certificate.yaml
  - ./ingressroute.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    version: 10.3.1
    valuesFile: values.yaml
    includeCRDs: true
    namespace: grafana
