apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: prometheus-tls-cert
  namespace: prometheus
spec:
  secretName: prometheus-tls-cert
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.zimmermann.sh
