apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus
resources:
  - ./namespace.yaml
  - ./certificate.yaml
  #- ./ingressroute.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    releaseName: prometheus
    version: 69.3.3
    valuesFile: values.yaml
    namespace: prometheus

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
