apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus
resources:
  - ./certificate.yaml
  #- ./ingress-route.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    releaseName: prometheus
    version: 82.2.1
    valuesFile: values.yaml
    namespace: prometheus
    includeCRDs: false

labels:
  - includeSelectors: false
    pairs:
      homelab.app: prometheus

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
  argocd.argoproj.io/compare-options: ServerSideDiff=true
  argocd.argoproj.io/sync-options: ServerSideApply=true
