apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource

metadata:
  name: mimir
  namespace: grafana-instance
spec:
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          name: grafana-instance-admin-credentials
          key: admin-user
          optional: true
    - targetPath: "basicAuthPassword"
      valueFrom:
        secretKeyRef:
          name: grafana-instance-admin-credentials
          key: admin-password
          optional: true
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://mimir-gateway.mimir.svc:8080/prometheus
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "30s"
  instanceSelector:
    matchLabels:
      dashboards: grafana

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource

metadata:
  name: loki
  namespace: grafana-instance
spec:
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          name: grafana-instance-admin-credentials
          key: admin-user
          optional: true
    - targetPath: "basicAuthPassword"
      valueFrom:
        secretKeyRef:
          name: grafana-instance-admin-credentials
          key: admin-password
          optional: true
  datasource:
    name: Loki
    type: loki
    access: proxy
    url: http://loki-gateway.loki.svc:80
    isDefault: false
    editable: false
  instanceSelector:
    matchLabels:
      dashboards: grafana
