apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana
resources:
  - ./namespace.yaml
  - ./sealedsecret.yaml
  - ./certificate.yaml
  - ./ingressroute.yaml
  - ./grafana.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: grafana

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
