apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-instance
resources:
  - ./namespace.yaml
  - ./datasources.yaml
  - ./sealedsecret.yaml
  - ./certificate.yaml
  - ./ingressroute.yaml

helmCharts:
  - name: grafana
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: grafana
    version: 8.6.4
    valuesFile: values.yaml
    namespace: grafana-instance
    includeCRDs: true

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: grafana

patches:
  # Service Patch - Fix Selector Collision
  - patch: |-
      - op: replace
        path: /spec/selector
        value:
          component: grafana-server
    target:
      kind: Service
      name: grafana

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
