apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-instance
resources:
  - ./namespace.yaml
  - ./datasources.yaml
  - ./sealed-secret.yaml
  - ./certificate.yaml
  - ./ingress-route.yaml

helmCharts:
  - name: grafana
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: grafana
    version: 10.5.15
    valuesFile: values.yaml
    namespace: grafana-instance
    includeCRDs: true


patches:
  # Configure LoadBalancer with Cilium BGP advertisement
  - target:
      kind: Service
      name: grafana
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/labels/bgp.cilium.io~1ip-pool
        value: default
      - op: add
        path: /metadata/labels/bgp.cilium.io~1advertise-service
        value: default

  # Service Patch - Fix Selector Collision
  - target:
      kind: Service
      name: grafana
    patch: |-
      - op: replace
        path: /spec/selector
        value:
          component: grafana-server

labels:
  - includeSelectors: false
    pairs:
      homelab.app: grafana-instance

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
