apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-instance
resources:
  - ./namespace.yaml
  - ./datasources.yaml
  - ./sealed-secret.yaml
  - ./certificate.yaml
  - ./ingress-route.yaml

helmCharts:
  - name: grafana
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: grafana
    version: 10.5.15
    valuesFile: values.yaml
    namespace: grafana-instance
    includeCRDs: true

labels:
  - includeSelectors: false
    pairs:
      homelab.app: grafana-instance

patches:
  # Service Patch - Fix Selector Collision
  - patch: |-
      - op: replace
        path: /spec/selector
        value:
          component: grafana-server
    target:
      kind: Service
      name: grafana

  # Deployment Patch - Allow immutable selector changes on chart upgrades
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana-image-renderer
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
    target:
      kind: Deployment
      name: grafana-image-renderer

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
