apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-admin-credentials
  namespace: grafana-instance
spec:
  encryptedData:
    admin-password: AgDCQ7BY0ntpGkLIqh7WzFMugs5JcK+7c6fb2KFcRo83z6K2GdgniSvFzKxCbN6Wwiev/q9kPTEs2ZOMfpg2ik+FI1MYNbZTzYf1sL5UuEdwS/OR3RxnunzUm7eTOl5rd5eF/wXgID75XbAQBjOj8wwm/MHPz2MRvtsYTkMu4PNMUiPxSex90lRcO+Y1qiqagzoaPevEOwdLghS9Rne6xKGD1s3LUUQ4h1Vu6qG8LvtfSUKh4VEjNQuQ5DFMj+ELYDnyoNHAAUa+N2GzhqVVnAagDCRQnNqWpKtOMn9Xx2M91IXmuaFpz1EBx+JAcw2k/heVBTzWP92uH52NmLPYaxUhPUD/jOv8S80kmUqVC6KUqNTEyArQX8fCC3l2Jn70sNI6HYnL7c29CnYKkSFjr58a0B1LQpsygeHMt/yeoc9IELikAOExNrqJGc6iygDPlWV7+ULXfXDjrO0gEbwrsYaB3BkEHvJfqvmDx1tDTZ8MzgZcC0bgUOiMLZqkoq510Z1+6S14aa/TSDbcoUovR4PV9TWHQbNfG3SGgFfy8o5ewR8CmdmojMlTznjrgt8UU7DrNWhUL36BaQ5hSjQ1ETbe1eq4pCL+wwjxzDsoG7LWggC539Ca6OIC54/9AEbslhHyjoRylmXcNkkudytUP79BZ4vUcIV1kzo4hutTJ0cvqLY17jsP3dDcfsqHew287yiUHXIX4lT9q1Lr/uIuuT/i4DUVNQ==
    admin-user: AgA09PqvrIQhutkD3AMjau4JOJNDzvFJlugKIyIfo4wzouFWN+I6wkOZ9L15vzlf4nNgVDGrhonlpiVCUMMSllBOtC1QZW+Irj/YKIo9zhWPyfOJ1QYfAp7if2Mm8DvP0hoeJuubPoVX4Fdevp01ViTNV8nO/42vB2HEgvCqcDykGGx48zjUhe2LmGNC+Y5YryH1IZD+FPghfAfr9lDHmRem9Wt263WXdkN6I3yR1587fCKMZ7w9wjQqyMASdXm1dF3dkElrdXPATAxatvYIguCImFHpACULX56lqPSE3hrRgQBBuzdneoPFcS/Ai6VLcD354sca/6DqXc2NSfsM70SLUjvsN7Xw1oC7u62h0j935cFxqQoyBAdxW+GVZZFe6H/w/Qt9XNG8imZ7S+cvpWR9SgSg94T3QGbA6QV6cvxeays7xR2IY6EY6Q7fAd+v68KHlVJLgaNQ4ycIH5OD4LF9emg92A78EOXVgK78VS0FfxAEF9EdLTEtYGdEfHWpM7KqcZFPc58hbzadfNdRhLOuA/oUSSsMCUJ7BVQfvozSV9Af8yhkuclxdegP6+JMp0vTaf9SOpFcmfaQXqGh9goWdYBlHOCu/BN3iHdnh8KWaEA7haMO/R1yi7bsQ9HeP2I8yToq0ErKt6v2ZZPueNEA2m9yGFFBUMdXjDp9gdkM574wKcj5uxzQ4DmW2dlnmpcIdggCnQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana-instance
    type: Opaque
