apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-admin-credentials
  namespace: grafana-instance
spec:
  encryptedData:
    admin-password: AgCYjJy3DUq5ut4NWWHjt0U1HzgjepeIpHkag5SwOayjIi0oGH+6h/gCs5uxC6rYf66QlpA75OhgEiFyxTzUcbwkI+E4Hd4e2Szy7nan8I4C4gcMZFGJTOYjT5jKn8svtyqLluPiLEITiGSLY1r8y9+PpSlhzGl/6l4t9dLKpXF+ASHouSGpfgZBOKP963fIT+BiH4KDbcwqYd/uKRX2sCX4Xh0zYbcccIWpPStAhhwEwkmddAMuenazSURlngtHa6n1qakc1EJg5cfmbqH1Cr+opfKveqq3ebypCc5L7EXEwwOb5F6W67q8guYBe12bb5/G9Gg+bDyOhf5+RVw5fwO/1eSz3wdH8Uao5EadbvG548TNK1rZgznv8YwoXj/dNmRorvHGuK16TY+3JNN8GktU4bRzAFpAF9mCsoiClIT/joqs3sBI7Ti6Rs6gbd0bCb9VBbR0GxBxYTyQhu22EXRYgfQk307VvVerg0qd0OGjE1kooeiJl5rLW3XDtBRFS/Ewy0J7Lz9beYxfXpGz2ysg69xYznKftP0u5Fwmnv0GTR77gjOZyLtg2iEjPIDodtBnLBERdSrgPqOVA57EOPwFFO39QaWqfQkh84EpcrnVwLKDU3hnVUKhmQr5KH2bPomKQFLEJ4Abc3PJaDQ3CYRCnRMjqD6ZJ3DtIKeqNzgqL2N4qoAD7oj/dkYTUIvHYG1CbmxEnlZUVG03RRcEgNSBzjRwtQ==
    admin-user: AgCaplpg10E1r/r7uQu2ZCc4P+uOrB34gAOLJCs9b2D1Wtvvcaq7/HOSkz9bboaP/wbw+5lDWsq4s8o99Sds0qqfEstJnNyfl5UX/BOtkHLc1R9i00/VMw/SQtrESiur1ZYc58FUIgewqhj4myHu7UwPwbSA7wprjq4XHIWI5jZ5F6ekEj4SKTe379sITwUfjMQlkslQO2FjCOEL2GYhMHfD2t9tReEhy0Yua5hC87/P7q0G2O7QJ5qQPHpziy2FZO+EB/EziVVTn88NRzCil9kOR7DvXB1PaVjJ9cGSXBTsU3aFVqPf7XPUQUI4Ok0h5Bym7YSqlI6zMucoMcKD83ObPbloZipqlSpCvWq3Ixoz91vMuK8QDq9F6hSD7zzwVXk4/qWN3cstyiUw1Onr0Ms/eAuDRBAVIA0jvdqxxzS/LRKMzlUySWGAo5/mCy4M4ptQZ1WhwV/xNgVVQ11EJ9IB0VjLZ8wYJSVGCXF17JNMG+2xI/uMA5c2ku6jF9d6ti+czM0rKq9tQzIaNV8WjqJkbrR19tAPFcgCZ9A4LQEaTa2tl6U6tyYgybD8rWx+XOFJIJA+hhpZluzjf2mf+/N7bwowxMDnDldq3xjFN+1ejcaYmjzxQ4eZBUUmb4m4WoKe5GMbo8MOdfkmkzWIIrH2xp/M/TswDWCxlbS4x/GyanPf2mjrvbGKm0xEjj8YPFWrXBv1eg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana-instance
    type: Opaque
