apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-admin-credentials
  namespace: grafana-instance
spec:
  encryptedData:
    admin-password: AgCbiEeJR3+xLBkgAbYj/medtE7guY2dPnBbjMdBSndusYpkTgbLLgg2940tGR1BHbOA5tVNLVpJz4keyUsgpnQ/i+GR3VVU4YIjPCWzQixsVmhG1wmI+MQY3nvbFJ+0qmKwpOMF0nVo6UnDT0MijcjCOL0W3GhWMSEBt6dnj8U2TAglbL5MLlRw2zMols3L6ntkc4aV4kUKP2whH1IyFKwdKFVLgHhFQHFyZqBCV2i/2bsbj/axxxiuP4WhzAacG8I6J7CIBrCeUrjUhzpvhCjrF1DMW/FtIZ1gAb4ZAqWDYLiIz3mmTDYeNCfOPHc3bMNPpT+Fnwv8BVsLvQMbd3BtDGr2PBwT7QFMOMbilkIUQsvOvnI7bUqAb5QRd/VqhWojfalXWls9LYCAtBlS3YJuDJ3dE9sUh5HSYbmkStQf10ATgTdsPxbiMm6yODD2XBNRAq0e0AbzDrFqLD34RyFK0SsjYc7wvhMFdP2/vZ4Yj2GHs5q08Ok15PC0Y1TpWBljpU3/dhB7CjlGX9wth7/4trILMv7utqEBx5pTOVu4XbDc/QTzq1BSghtsLElyaiwcq4XxUbfKXmL/4zLlFKCSicJ4kBtZsmhRGH/i1CTB2JbsxjckSG+b4Ruu27YD2slTi93EnnF0UomzmiAN4WUnhQv2FBTljBwltsFEg1UWzJ77zv72ZtkVhes2HkQdMAUO+PUA1U5i3kixH2z4MVgpHSNIDg==
    admin-user: AgBzzgxek58plAxchcz5EPes1NOvl2YOAemu+1g6eYHpUAwu7zR/lxQuNp9fvB/3gVoAULk1tBALVHmqFFZPAILbU70TvCVkmPzPZv2D3XwBwN48WKOUInibITDtnxAV39KstrIO0WtUEXgg3lipus7JMSUU3mx0h792VFJM+W/y7hb7LaJupi87izB/qQ3HvAJ2ieqrsSh2YiSGLhAsu9e/6E8xicqi0eCM6LGhjgq1IimsmgFPB5K+fiLSXg0LCCaRXV1fxm2V/C/YU/7YNFRmI/z6ewCrtC/YNV73QVYVYZhNezb5S9gGOrOjcMVc1G1e/oQeWMWsY6MZg9n2SpWNEis5/NRtKaZ3FvyBRlMDHFfQOriGn6uspIZr2J1oNpMGJO13fDhV7VCkmbTPR/EmupHlGbTD2cqrC7DVKbyk3lqQhw4p2AsI6eKxC1EDPQbPRwREzlXgi+7auHGOlj8xAfdrC2uhczZJXmkKkMaiCFauVnhAzGQVid9F1z+i2x1SJkwlppsiWRDl6YDdz5J44m6e0vLPYkp0LK3jY/3aTEANJfdqXsY34bKhThJe5oGlZvyH9Ev67H8bYe/a4AtvRq0s0lwmfYNws5hmxuU7KpfwOqsmPQDGjOP4T3Ep39CnQNexLJXxE38YnzJM5OBiwGpUaH7SungZxh+2O15kmMNht3TQC8YEfYIWnTrs54Buy8HYAw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana-instance
