---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-instance-admin-credentials
  namespace: grafana-instance
spec:
  encryptedData:
    admin-password: AgBvgPLL+wGvON52jUUXd7tljMtH8UWKe+1FMxzp13qsilKokXzUyXJwSTnmXMQYHcvkDM6PPGGhn7Wj0291/rh4dlVfDviOLSSzcIH4KYgz+dbKd6i4acXvgbdWhvx6BWu8KJ8BTk8hetFGEU9D0zej6/R9bU3OFnjrB4E5nlJiWxJiodER2TgOzpeHHJBhQS933BVwS2gzL2iZ8pXa5DmV/daQxlz0nhljgw1ekg3bI5VFX7JZxa1ZMSvMJ1uJehCQFPTqXePq22HqDzQxxcTCSo8+Cg70IArH5p3zGKtPuw59Fe9tAA/ry0MVntbTPMPJfviipTs8LBMDn5gBmthDH1XcK5kIPpJCyK5NIk74LONg9aB6rFavrUJvOxcfn4GZbxv/PHLJpiKoRF9JtsV26UOghqixDOsnLJTyJmjeA1PLSEOzO63uSkTUeGfV9rBJ/GNwF4eqSsASHgpT0Mwb27eSTg8bkKCPGgAxkH4m+lQ9NicW3OTLzNLzc5XN9hRDklzcAEKaiRKqLNA6fYyoqL/+IZbDcCI9FiOwXuWPmL3fbJxze68q7ljolTCCusDH/SJJORqv6TuI5zU6juNJx7E2G52Fe3HB3NMqZoWt5O0W6z6AMfec3dP67FkFjDC19RhMSqFFHXWtXYaN8USiuw+8cUPKvnETeNvdQ3/VwJ3G5Y+jbWDFVXnA0qsqvF0hr2U51ORxN0HKzBynQItwnr8EJg==
    admin-user: AgDBPjatCqRaKL8Iz8BPE1ZksXf3VRd5PIfI1m5tzAiBgdbCVajNiYG9Fcp2jF877N49V71tCaWn+SR2uKUCb/FA+3fL3UHm13EWSTU5vZNeQ1FuwPD3JGfb+lLnY0dSo/CsUc9anqwcM6S7nUXbyQ4WFryb8rb23qzvEuXne86JzNGsWVYybKZcLHRNkk9oCxpKKeGJmKvU40iJ828/5GtAbLDiqQWMoUVVj2+niaDn1Np7cxlgevsZWo7MXx3uJUFq+xgY05Yrv7N4HgoJsOeWYH4s0WBmy/m9ilDl+FrpVEyrxfLmTVbR+IxhpKW31OoBUpHKy/0NQ06Dk7Pgsv8UD34NjY8WKhYkTADAXGlTuw9V/zI/4KDQASMmLBVEO2hx0pJPRcwymvKEW5XR5nPuyGbKYxP5ExFZ+C1WoE9uwOUTUYIfRF+vSp2Tga1m9Yd8LwKvt5fwU/eH59F5GSeo9V5sUIuPGaYWhXh1PysXydBC/rm2Z5tvfVWNZUrVKWM75wEElpFz3mylao3hVHdmTged64kD8oyr9Cp+fiOTpISmX8WdTaWEqie2HUKodwopqF+a7v9OZXtgrTrYURUaSVP9KDcAAIvAJe8POpzjtdshTevnXjHh8sJlsZcIDxPz863UQQRhLTWRCpizm578+HP2liH7d6pEqG7xaoZOyqwfzbC0A4NZ5aNvJrLkVbpEJL6q5A==
  template:
    metadata:
      name: grafana-instance-admin-credentials
      namespace: grafana-instance
