---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: grafana-instance
spec:
  encryptedData:
    admin-password: AgDCfoVp27pnkfKILTMX4EYlxbCJBhpHUfNc0qRMk7QZOwroWKuWkwSdKgWGw5yR2TyMB3cPq2EdL7SBHK5ekfszhT/ayBPIJhSnT4NPDUrdJ2xvjZy6NYxQ4RVAKoa13GQedqdosgcj1mvO/SnttXRS2AX6+Tc8xpvFup0+dy8p4vEzK9MaftTSf/fsDvacPQ4vByDNFJrXhZndAQviV2SwXYugHdKn+LYZQDEgtLIKW10U5gNqR/+VBnpB6dgVUOygEQxXDACz7xruMGQm7UCom7dK8zhXGFV7WDVw1Q6+qBQKPzoCsx/dOk7KUa5BW8sk9GSJTG+OtMNRISrQKmvTHJpmQCEmuA4YRmNNvov23zRC1IdrThh5/7Khk+BaLf7dMyVKmmQtln9k0XVOQybtwBvR+Tv5xj4mc47VXLH68tUPPCj7p85khrA8eZ1obLYAiesUt7B0aICuG44aHwgmVDgBaG/NqI7d8bzqcAAL+9z/tiqhkY6TzTywEhiZUipcXwQRNjuLkV7n0ZP6+ejM43hOKUrSbuIFbVGjkkoTEG+jWly8Fdtg/pWSA41mev28fYs3ETN4kY6Kw87T65Xu3QLVZQkFVfh15CcN8jtKOxc3YKkerjMeQCu2aVvzWEB5j0YTE2BZEyp30R3fmuCeh9M8GCapjoxSvL01QEA66NP2aisIUwhA0yWo1x5JPyWMgSgYuqMHBi62a4E8Y+YyFijrjQ==
    admin-user: AgCHytvWWLFyw2p1uYCv1x+mHDRMaAlS63llEFuIY+YHeDMY+7aMe6fLpqqkgAQa2gi1d2pR2u3g+Gi0f290dZ9But6DKsc82D2QbHvitjJQjVqzNrhf48i0kmlkrWlfukwfYqSMjoOBgvTVDFJHXKj4X9f7GKp9+HCF7TdkfNhNquIA71N6CrE+0kqDhhvS+2RLXguddBNkI46vG5F4WQ1Vc0yQ8+hGxTTYl5IQCu6xno+odOFbieLiwr6/0OPJYFyV8/jRcIjD+tm17gyPRiIaUFBZbBsSxoH5g83Jf0e3uQTkC8e9qVUnV/Wc7Dbe2HhAavVLU4CrcXwHtgI+G1oUlLlGuEl3p8V2m5xeLc5IiV1oRzxHfG/PCDHIVmUd3x7kQJcViFR3E5REU06YnwWO5LjvoHTFCHlzO4wYRpFVgUK8cffsfzrOHpGAU7eAaLfmrk0flQmr1SdGu+toHtPfWEUd/8ShMS9VlM2ssexq3kVU88yCq7VEVNVgQ9xD51rTvWP0+PY/Ua97UM3f9/wkWxP54PtCxTz38Qn+LFD+aMQRqizwx7SH3giuRQ9yvhPZ4HgNZjUC+o4lJZjPg+UpxEJrEH8a2AV79FMWKrTIc5VNSKdjPhce99RfQbxyWW2n5s6t2jgmcVK8pFU1phplzUwNeP9sfc+gvvnm21Nymz+J4r5AFmOxmOyghv3JkDxQeSDyEw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana-instance
