---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-instance-admin-credentials
  namespace: grafana-instance
spec:
  encryptedData:
    admin-password: AgCYnUZFjSzGY+SBLxg/OLY3u8l7mQiOI9C4X9+tZ94c4HrV+qvdLwrJcd78EGw9Sc1RN/Q1N6bTSiE9GqUMvTErQRzxtwYatEGOZ1gcW6bHAecpT0y5I8vowVbSh3YIUVL6h+kDWdYoVH9C3kOBRjgnO4nLpjvSh1cPysmSBpnsrmFOSEJk8KUfC0EhOxd7iuV4DmQvomIicyvLL46fH3DPfQERxB/C7MW3K1E9z3mK+P3KL6VMlWSXBGmNbvAnhMpfwiq9bh2auNCVMX81yah4JQ8yrFq7wTCzC9CX64AO2zHO8BVry/oLdUDD89pnefxd5bvTEp51i3qVk8OifVHQVEgK5+AyCmULbT/fPaNNdr6HjidZ9asOCfXkxG7NIJMoy2lBIVlC0iYjmhoQ6sbgEXL8MsFIsdYLlr9LfRPLuu/tUwn2IfPHOSMA2R0Kf1nT9o+0WKfOiwByjUaMnwwAOaNP6QF81yohBSwkaPljqkeadLU/Dq1TJBW11wbdPFkmlJXRiLffvcxLSZUQIdr9RWmtiyGgOjyBoRFoYNeJ+cKBQczt+TEAHBMY/wee9AJpz0p+LtI76Pe+Eyzc34zZALAOy+qYxukiJHwOkR1hlhyHC0E0Pktn5AqcApTA3ZWy0ZxREojrieCCQsaBa/Gj7kp1cm+EU4Glfue6H7KSZvtCPx+/E+RHjBHGaQ/fYDuc2WbhJwaG7g8vAcyg1AE7KDHQyw==
    admin-user: AgC9/OCnCPKZpSlYesw/Xz07ACadAdpO22Fpl2fToIJXzfMtSqnHZhgDjtHOqHONWGTzjH73D4wWfeZgbmuv0WAe+ZjPBpYAFk+LT/9PDMp4Nf4VTd88xW8okqZ+uWekBADwxx3xokCT8pnignJylOL49stVoY2zD7/tvrXixJxloYz/7Ky21CB8nB4ZkFUddLrko1dBFmH4go7TZ/2XtymBW+aKI13G8LDK+CWpVll9no+h6JZzTbQNkqBbzIKfeGbHHSM5e30WsPBh4b1OFqvvEkUNsUSTKuzBQXWytKHbADXW5kfzm3Ulj/RazKE6vrJv0dQIT9NG76zHtL8uOrTBLpBVv4EPvvo0iX/Qy3p4JSJ26Tdzp5TwhUspgAv1G12HAaFpJOhKWFxx+Jhv90a+7ip3OkbRKsnjydrPcW8b2SUwwYp4sP7Xi4MypMmim8+9KvJ8nbKbs/PsxwCa49unfxNpt0vPL7uoyZNVU6H84rZAkxEEGxcqgBjQOyGpJlWiIvQbtGmyGjwc8QQbOvqradY5Ho46/DXi7VXakiGYsn/MmQ1O4zMg7PKMY+tFbg2825phGsdqV4airDR3AksohC3JUE3VAF1z20qTLrs2BGNrGDe/stqVmdj2r1vtuAxWpyVP8u10BJFM3AitUNqexs+L/L2oBmH3croQemIVkIO7th425916iavOBHdo0JqueSJOHg==
  template:
    metadata:
      name: grafana-instance-admin-credentials
      namespace: grafana-instance
