apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: grafana-admin-credentials
  namespace: grafana-instance
spec:
  encryptedData:
    admin-password: AgAIjUA//lcT/tPF3q8gR0b+W9bH4AC7EAtK9pQOJaf84oE2EV0ebeBF0OHYv548tedRRnL48xK/jZBATYwHviJYOVfzswQz+8S/0GITJRolSsdgQ12qBTiyMiI+JlIxz6b/aGny9Dg/itxmx17z+Y30ZDaYSWR9OPyYGsbXaUkMT6L8cOr9NQNA7/UXcQeOP1x8WEdCQo2LZYgVsYfpTcOkLLxekdU70jIMQsRuOSBET/BakDBHXn6XhTXfGXXw6r7eVUqC27XAVlgWLRqO19NXMIR14iKMBaoN0j5CHXMivBcZkzNaRqIpeF958zuveisWz4irWGXcI1J360xTRXe1NSH3YVNzRGfK9VBII84D+GOhkHRqJIT91oeab/8hpKwNWyRujIEmlLGodsYlSVp+NLbqhJJav+MteWLXvFe9r0DJJJZXy0HMjhrxodQrCYIUUgYKSQdp8R46KqTll1a8sRYjiDNFmmeVHgYYr8xmhZRl9fAT5hVLJIQPb220w2+eXWcx7pTVqT6Zu0dY655pUGbkM0gWzcHEQGAFl3YxkOIue2BjHgY2o8FoMDh9Y63XGBPgx21nIe5dtjZodMoneMFoCSfZvDUzF8MKSCsEOLIV5wpbLwk5z2yiJURO4MAsgMAPHdPiOsQkAynH0aNZ36QY1gg7aVFtwoyKiiugzP9pta+tuBPWe0SSm3MNTxgoaIhYkB7i/PytP5xzETLw0c944A==
    admin-user: AgANMQMXsf20eT907oPfzi9oaxMH9brcfpD9nUzzQWa3pGleAQTiOVZZNZ5MiLcSryiwtdhBeSxccV+jUs3s78dIhWZlgzSTxEpZ2Ye++9cQ9D7oZsns2rnZWRdYn1CGGy9+YKF4qngFazqgMO5GMHRqLFhAa3MxXRJLPJ4mlqDs43VfNK+rIXJCdzKKt9OD+t870/ltNq+gkDOinsRqqCGQ6HMiUuNRXPaFvZLu/G2hsBAKB+RKNC0EXXDDueGhr6lFlV4Yt9YBqq6iyf90DI741epp3nYOw6njIqNz2NZpVDU2MtfYhWSAXe+Uugi/Im8RJYemAo2Ov9VAldGsREU9Ug+Oo78/ZVP5ZtKYP7qZThK6be73Y0BVBJpupfo/j1Em8WwaMH44HqP5hkkio1Pder2hOMV9FWhgtLpxK5BpEyaQTw938B/OjecfJifdHW8Zjn7S9fOZb9X5OC1YU+qooghAOSyBqQnHSp5TvZxVL1jS0tc16fr4k/0diAIT4rGktHgkHLplslxrqlNFK8GI2y0WpMGAPALAaJ61Z0msyOQRXHmi5KvlKjTqRKLVAP146Sy/37gSKQ7Edb5tQdm7EWx3O6Utpv6iedyVUxVoXJ6jjanEIiuzO4fgUM/Qli+0OkbFqWB2fkULxoSYnoOoWmvr4oe6HFO4zU9U5+pXu2BXwKX3R070I0AJvKR3nYyMJl/GBQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana-instance
    type: Opaque
