apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: rustfs-console-tls
  namespace: rustfs
spec:
  secretName: rustfs-console-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - PLACEHOLDER
