apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: rustfs-console
  namespace: rustfs
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`console.rustfs.zimmermann.sh`)
      priority: 10
      services:
        - kind: Service
          name: rustfs-svc
          port: 9001
  tls:
    secretName: rustfs-console-tls
