apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rustfs
resources:
  - ./namespace.yaml
  - ./ingress-route.yaml
  - ./certificate.yaml
  - ./sealed-secret.yaml

helmCharts:
  - name: rustfs
    repo: https://rustfs.github.io/helm
    releaseName: rustfs
    version: 0.0.79
    valuesFile: values.yaml
    namespace: rustfs

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: rustfs

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
