apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rustfs
resources:
  - ./namespace.yaml
  - ./ingress-route.yaml
  - ./certificate.yaml
  - ./sealed-secret.yaml

helmCharts:
  - name: rustfs
    repo: https://rustfs.github.io/helm
    releaseName: rustfs
    version: 0.0.79
    valuesFile: values.yaml
    namespace: rustfs

patches:
  # Configure LoadBalancer with Cilium BGP advertisement
  - target:
      kind: Service
      name: rustfs-svc
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/labels/bgp.cilium.io~1ip-pool
        value: default
      - op: add
        path: /metadata/labels/bgp.cilium.io~1advertise-service
        value: default

labels:
  - includeSelectors: false
    pairs:
      homelab.app: rustfs

commonAnnotations:
  argocd.argoproj.io/sync-wave: "8"
