---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-admin-credentials
  namespace: rustfs
spec:
  encryptedData:
    access-key: AgB+yCtGDrfR6cWUpSFKbMbrqz3SIx8wMffuqZJ2iIwFWRDkzA6Ws+OGa97i7+nIvox5TcBerGf4IE6MsK1QkUN1ojNpeA+HU7Me9vyCae4YXNZcrBAKAb9Ekx3puHBmxaSrDcjF62LMD1VpjtPtMdoqz3/TjuljVveNlBsqLOmMrl1r5n+s91zCuJ5jaqYBJ/b+/avZH2+E+m8a4V5XmsIdck0AMqFFGzKZhv4fYxNDeYcb5rcYhK2gxDqJ50OxGcVV82L5JHi0QXixr2Lub0/pXkzPdDw/sZprz3HKIWsVyt/YYC5V/t1vCNHMaIGtHf92lnnL6X8xJIuzeYY6bN8zXfDqMWkVBI04CGc3yWpBqR3QtPDHbk7poXGHHEYMtbYEA0E9GGNg4H8by6kCW++GIqlAWf78Pggf/dUBgSwnviSrgOP0YBBjW5Rd/WEiObaYiDvKNErwl4Yd+VvhKh3pLXHdWqR3sC4o6juNqQTE/r92kxXyY5nQ/Sj3o0tUmMT3q5rVPItY2GzeEaNdTGMOwxU7Lr+NvR1s8kAX0vifAHZsTnhYnGtX/GpnYxgnp+UAYqmX6x8JUTSl6/lVEjKXeJDScsX8paLJQYYY20+5RiaaE8FnsY+PGo3PdMAoln/T8evpMmBvJOMD78osaa9eXxcCwcMjctB6Z/hSE20yYp41OErYfnC5F/cNW64mmlAWXIdwT4/qeCIXSg==
    secret-key: AgCSBMwWnhXXw6e5ZfqbbaJo8FPfoVjzq12QiwpJJZJ/B+guL6LGXF0ze5lmut22n2kH+OaLge0cJEFj5a2w2JKYJJGGashFBO/S+j6AqaFE3MA5GWerag3Hd3VhDYvxs8jkXNxWfLI1HMhSyQATn5/w6+9gO/dbgeP55eets6O8W4WO7aDKMf0vLZd3VEB8oJGUFSBwBAH/LC9+IvEIgdQ2ZWEMeo9ECjEa7Zpq15v5zQ2vdrogHrVKyv6jBlTp450HWeZ6VdAaIvfIpfdnI8I4H2kEOero6FLuZiks9uCZw6iXwP8znF/OzsMUk9HS5TZpHyrqm7REcgejU71FP0AmDB1RMIUFrcLaFE7OlL/YmPxwyRqLT7BV+vfDjhmM+tVftUe5oeamTWixQbfaIfQsSvo2Js0zNjHFCYBArr1lGkrj7g8syIfCw/FX870cB9jCK9qEAihcVvGyXwKsKFYyljm7G3VjiOLu2Jb5ZZt5UtXN7t7aaDukqWHmIDzt2tZCE+msTKXTo3hGuqzF2j8F0XmNR47F5LauxmhB/wiCd+x2Oth+Ccqm7rCy+JflXirXYf8czrWysqme19OhY8BZU4YVMeeDTsRlNpcb1mTUm49w59/HYmFWrmWv5yYCfpV9V0t04q/D4l3zte5RLcSfopi6P+bPCLgitYp0YPvZkAzCvW0G98xSJboXRJS0rHZQZbNPOAzKCWUAOjZls2dkWoiGIBfH88bklzuuJHXnI7o5
  template:
    metadata:
      name: rustfs-admin-credentials
      namespace: rustfs
    type: Opaque
