apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-admin-credentials
  namespace: rustfs
spec:
  encryptedData:
    access-key: AgDIrAs7tRb6dLdDmeXOJ87g09py/usNH3TddurZCX074Kubwb5DPUuOv4YxsOiHEbKJDuCVBpXO1cm/GXEm++yY5Y/0IH7hMUp2dVD5QPIokd9tJNNI8UH+R+tKLa4DDFOa6Ngkwwswy9gyfr/E6+3ipOmQ+JbuMjhUnOrAHKmMSWlnbdxym/VXHY4szzI65MUg5qpB0vMM95l1vxX7mlMTr1B6w+Lu+kcYopX7HMZzjoXFV9Cna1jwHqBliJdFh+Cymkk0PUucSvNyRrq0Ajw6HhCsWkxAA24ebP/zBzpzca7zXXHOqejrdqhiAP2M9gWvM0HwJBKeGTVGXZjBBlMu1bTrc7mz368yO1Hy/PrB1hoWyKFtu93+9fKjkERV5qkpO+ssUVDZoWCXoEAYqwuuVHWNMaBQdBDxNi1LK4un0WZvF/qIaT7jW/SHxEVxHnc5a4S1EFjncGY9e3J30RgmXpJiYcPlx2R8ODatg/xoQaOx62YS/dDIsGro6zvyfaEy+DrYEsNS34uR1H3h2glc/rQhsub6A4sHRwEmSA1oczj6ywEKTr3scSSodRF05RSDy6IUmB9hUNzsx9HjEqinlvv86rVqn5/7T7i9C5x2N+bJ2wlb7Q+7cq5iaYh+bXt0eKn9u0HZLheBCvoEAOheUkYMcyUXPtcsqyaeBSpVjrJWMC3wuICSzhuN+tmShFfRCespB6kHtcqvsg==
    secret-key: AgBAZpGj2pEWlO0YXm0BoG9whs5wmNpFWX0UEBLlqcSHwXK7tOrk98J8ZmCzCFIzPCHiV8v6QQnyEGkjZ04IJW8ppyXPViEZNNFu+6Xc7qDLSlectPjw+iDkCyWO4LDDGCe+woaOoRCPT87f3Tq/AVBSvIwbVbTnTnqQnkCiz5dxol8FoikxGFriCO9rf7kwkWWcGIoePTtdAi4l7+yD0+z1PUx6KtA6+imNggekLNhDmqwvfh73WPePfbjTXHahIX0j9+a77VwwTm0u3BzIQB4H4IxpYdJ4X3bDdIkvceSwf3qJ1WVxV22iI4zfWxawv18Ou+ZJU+BUwPwCiVDIr8U0tOIDx0XrpzffsUPmIHhA3hVCziH1iS09FKqlL1wRMsy/yPqs4dj68ngZFbUZq+t3KZ6GqKLgCmRIusy+oUQJi2bnHIIEQqKDTtphnnemAPXvhYcRc9halLMG5zdhkzqVvLKf2gLJrG7RopV3IoiGl4jA6JpSlhSN5lhPgwcb2soEm2MJs5oDoWrOfyFGuCAgGeUSK2+fDAcHUp8R68rJ+/4RPITrn11x4+2ebuF1i1EivMjkV8FImcBMUmo3LF9hJXquDom4OWcg2Gss8e9SN6V4zaMKv4cSWdssnV7ej0baMB6pTT30YfyNNXaglu8CdcyvYhWHDtPaLcgIGH3xhaGlkgC0On192hWu/7vOal1wr/Uj2kJWVKp40q/8fybvEufv2EjJZOIqcXz+DrJ/7TXF
  template:
    metadata:
      name: rustfs-admin-credentials
      namespace: rustfs
    type: Opaque
