---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secret
  namespace: rustfs
spec:
  encryptedData:
    access-key: AgCxxhrk5HbXFNPVWqXzaROOYQJ/e/Q0SAlSpQQSmKXd+j1IyDbl6iXbs3k7LXD2VY8UdZaASzOUCKiVK1gwNfoDBBd1+ju5xQaDLxjEjXbkgmLc/RT7qE648YAT4B5ZGW/wYfEB+JBtQk1XbV7xfCZppaPHsGbUon7q2iTmoKrkrtq+DNQHJcUGxJyu5IkmzkayziXdGsgay/CkIHAN+KZn9zR2GGL0eJefAdXOzVkOfLAOHP4wB6vDl4bluSAGEhdsfbYK1wGAsRlsNjTamNbU+MF6aAukAGFZoQTlQljv0zbbgvYxJnhf0v0UgBMg6gtDdLy8aqZD8GR+pYEk+wWCJkFnJ5Lfc5I53lKgAp20i7bCXOn7C0p5nn0187ewat7QDn2v0TFsS0gpxSj9kIfNFdZKz2NiSTiSRcuGNBW4ZbpSXkeYou9aPkNjxXJhpOUw6Jv467HL7rbug9S9iaCJjSprrrO4C6t7WrGCaou+YHWfjtfSWWuMkJ9kN0sqDalfonhdAOJ7/ACcqZG/Dk6jEwSsNBCNjy6qjeD7+P1s3/YrS09IWUxWIZ3DSDK69dCeI6A3jYJrvINP1ZIv1fT3V2iDH4rMJT+lKSNYfXKATjqjrlJLZ3ABmTEN7vvbF+dY+y0k8iZOVUA6VpKLUg8b5anRjCgi3d8RWTj/5oUUZEGkcPyjY94r59N4P7FLPjzia9T7HgvYdgsVmQ==
    secret-key: AgCPE+8bW4SPPErJS09EsVu9ollHHA7FSJG/R1OZDCacdVv4cOsRG6tFMzglqGi/w+4vw3urThZ/wpJczulhbjob8oDTeSYCFx9REDiEKSJVqAYxy7RaE9ZeqAcnBpKpsAQ9LBgfXCP9Vzmahb2SmNdngSAdiUVgQhqrfqE9XCuJVnND1Y4FyB9/UuOnxGHUzLi6JSI3N834ic8zi2lHn8Y6HU9izZTUL4Z2y2KdGMZSVcrKth9iLmT6noGMxZeXOUCQoDKq2ByHfFVmhsHUOax+qLB+u1L4kDmcmBvfr9Rpwt8li4fVT9E0N3qzFhq+Hr9NdGo5El7FkT276iEXV4Qm8KxQrxav7GCz2GpFDBG0q5n0O9XEIZt+kfpuJsF3tt9WYpYo19URaOaI4tgPimekhJXVRSOvNG5lpJNGN3edvUU94OV8l7UEliCK8TxGcsTIE1ODLqeT4G1A9mRGGWW4oygg0av5f4rHRdy1vzY3owWGuKuVXqwgelooVJ/EHLI26yUUcTzwn0CKbjqugYECBeBmLwqlYtWjBdbq7UtxkCdHgwoAXD/qJS+1hZ6w8kBh37zV+s8vfNe2L1pxwh60ZeON89FAQByhHL+jl2nk87nJak764YYV49XBd6UL046Nk7lLasvz3+c6bUb7w4aZBnqa0KgJW0loCDnF1AaYEVWgkkOkzWwgvqdWIag2G8T2YVI4zZgZ4I32vA==
  template:
    metadata:
      name: rustfs-secret
      namespace: rustfs
    type: Opaque
