apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: rustfs-admin-credentials
  namespace: rustfs
spec:
  encryptedData:
    access-key: AgAVitlmmdJ+8eDILlE5daP9go6UhX64pojcOu1ER23AjYw7Tw+aYcnedKo7i85G9WDQvOgZuYrp8LZY2UgesW0B3FW5K210iw4Y8J+m9v26Y5VXnpj2bkyYqaOvEC7mll70vsKg7aNlmBO3+S0KqfxuTBVE6ipFNoEoc71zPZH8s6eZptnkCqSX+KgYg9o/pKWvZg6B1bgAh/CGWHlF3rVW2F1YHHNXUBsvdHt9+wPPZcEDyNRtDMYwBLzzSkz4L53CjOYrT2/r3DoZukKjlonBo0TWY0SIMkLS6wKLxV/D0r/ffJh3uA7A+E0AQmz6X6kps9W1SY5s6mdXjRcWavjbLQTU25G25BCSYbUko2rSJjuTNGhFYnGZ4YKlPS4UfuGE3v6s0v3+FgfCE+V669baGciNrS93CGceelhef0iA9UQHTFZtsrZxxZS+2kLP+/nwSbLMFjYu1w5rFAvkw6LOfC7/V4AfiLUtcqb1KwlK/6aVJhBXCJbZDBH/80bLxKeaqQeeV1VC4xlTuGAM9Dh493tvuUvqjYTloCCYpKXl9J9sf9/U/kU0OIA8Aaih1URZvOfDM+D3GfF1MhKm2S9xJJGdrShHO4vHXhLMa/3nks5gGtuhcVD1yXUCB47ii9DNllzDJw4tXoNra9esW/5L2aMUZfogtBgbNydQUDI+pi50f2jZKJDypCFUS1RDIDKtOUcU/X1L2YqDeA==
    secret-key: AgBXwc2ownnzuBZYE2FoJSxxDSgU+8b2aU01D38+GdNuSxsash1y8PjJEJWsI7oAMp40YRQk9jZuHak2iNPI+96O4AKm7nfnPfSqJVcJWByv9lCwu6zVc7E+U5RP4o1NK01i/F5KG1+xbOvA7F1cM14K1Ji4tSxP7ToEjr2bPTtCuuKGls7ujfQWbL2N+xTHtsTUcYWMAGz8XrX6LDMxHshpwtN8yLtihf8eIlrQEOJkciZKpvRdSmImI5QKVUA7uWFR1XQMO6tIK4BEE/buxProj3bntVTK2ZijGgz3Qyx6FhxxKWAV372/xY1go7I1HdSH1Eh8AzzsPd5k6PX5H7OO1NmAIZlD7BQRpCD5QwbMnzRohAu04StinR7yCazmgy4mEPyKjP3DhvkePgKL/1IxRxeveqxXl/o5Bx667xFjLTi835AbxBBA2gSI2lP5iP/DO2p1AVdPmP7dbfy1KPUR+CUL+MPT6LteX/iBSzEd/u/qoy49ywTpijFfcwUweQ4wAUW1H/G6xF6MtNeg9CBmKjilBT8ulu0Nzm+DmwPv3HnFrNyIRNgsQ0BzNjcOyHKoa59isK/rsKH2vrPLB0ybz/2SAw6LG4ZTNSiHyYOksSm21GBL7ZzmjY0JZEpysfuNvpCFjqBme6EkNoecysieJ+DpqD+VRmq6S1ikNCm7y9z6PeuoVUh052ya/wu5/uog9QDQ9yBo9rTsES0NHIzuTzgyGupNL2eUaxn8DBKg/BOl
  template:
    metadata:
      name: rustfs-admin-credentials
      namespace: rustfs
    type: Opaque
