---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-admin-credentials
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgDACTT+HXxQM3vnLmbX/49mcGF5UHIL+6Odys2OOpY/P6XYk6pMqcr7AxqbShEq8gEswLWysKlc3iXrv9Vj1HwPCPkl5r5iHTVjhOJF2y/7lMqMoQn1hH4+Cr5h4f8Hkj7u2qCVdZr36qEIeJfZ4k8zhS6+RMJVTcSaKGVUeDp9Vbe1K1WGHK0c7TvOZff4ise/lQYYeDzeMgYMVEkFsCZInqLcQoGZJUErtZcsH8xDBPsSSRGDQArF2wVhradJTrOWm7mxDdMUQJGwQ6Glx6sGQKkeqqD306n+U/eMEC3x/PA1DRTLr+1XEvmhCULx+i8pcjGI1m0UArkczyR45BaBxcY9A3Ov8uJoaYuLEl1z7rplmXhnCUmdky2cjJW6U3YvNwaHFeqP20clTbh8TBbE6jwH4gpVR+FTmZI9MXhaR7L7fd6CuXExe5jto3dkffC41uqq/BYcRBs+xMNB/NL7semAP0QiKjDqD50oRVX6BBdBuYD/8i9qrftwOVZQkgNNZuSc3p23wJuIOmLvJiaDKyq/VmuT+/GWtY7wGpKMwsjTOEzjB8uf+23982rs2UBLJ9oHM96zQZdaTdO6E259IziOFScQJ+0zXeUIafAYbrnXfkdrfNBGqxJJ6LFzOpZPeFwqOBTcLY5p9Yotidgq56FcNM70vkjbTqC9iFj8wGzNGVw+wcKebXN9ACefmDFDNTokkeRyhszqEA==
    RUSTFS_SECRET_KEY: AgCdH3vNMjrHHPzgAMVMXCIArwveySHUQMbksV8B5X2NOh0bZ4u3snmCX7vAOdtPkfyM8Vxdy6tDvex1/8dXvaJ5W5THLJ/G4FAnvMGZQK1D55W0QGYQadbhN8uMGMWKmef170E6lryw5zUa9X8S/4Gb7JNpHaGqKObkNv3TDuMq1aVLFyxtioWSIeEELaKAs8UEdrjMlpxPKE1UVh05RfIf8fD3v9ZO+HcjJoI04vvTZV+qH9Trn3IEom2+nPzLsDDXXGZAYwdNzoNTGq6DBiRw7r/GIKdOY1HfY/Nvm2f7bj1KSQWw0KKfKPl9Ia5lKSgSsXFhyZEWMS11X34A8U6go77bOg/4lr/eYFkg1OgE/Q6RQJ5itrns02pZ76t+26TJ1tIY2U06caB+Q+TaTfCXT6bdripQNDDGUw0qH/MtBKzVPP20rLI6vbvvV1T8hXNNGMzAdJ+OOQhQlSyMIB8XRcGhNTAgtRfNrc0Va1hXN/W8YII8urSMG1ibYTXxMYfKC6ZsDoIyu2t4YB56F35hm9T09H/hnu50yBbzVZDkMKFgWZrk7zzDeVb2n0EfZ7faV4btguxPndL7GoVU4kS0TNDq0R7hG9xywrdbdHyke30GRxWUIphDPY34WgR08x88RW+odoBr4YETS6cNgHsPzkAl3qofCNdWK/qRYXBtUv8F0jIG+eY3ImLbKhnS52VzigLJKKOqPTjJjYvXiT8JvQCNMqStRTCftFT5TfeKlhct
  template:
    metadata:
      name: rustfs-admin-credentials
      namespace: rustfs
    type: Opaque
