apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-controller
resources:
  - ./namespace.yaml
  - ./certificate.yaml

helmCharts:
  - name: traefik
    repo: oci://ghcr.io/traefik/helm
    releaseName: traefik
    version: 38.0.1
    valuesFile: values.yaml
    namespace: ingress-controller
    includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
