apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-controller
resources:
  - ./namespace.yaml
  - ./certificate.yaml

helmCharts:
  - name: traefik
    repo: oci://ghcr.io/traefik/helm
    releaseName: traefik
    version: 39.0.2
    valuesFile: values.yaml
    namespace: ingress-controller
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1
      - policy/v1/PodDisruptionBudget

labels:
  - includeSelectors: false
    pairs:
      homelab.component: ingress-controller

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-8"
