apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-controller
resources:
  - ./namespace.yaml
  - ./certificate.yaml

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    releaseName: traefik
    version: 38.0.1
    valuesFile: values.yaml
    includeCRDs: true
    namespace: ingress-controller

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: traefik
        labels:
          bgp.cilium.io/ip-pool: default
          bgp.cilium.io/advertise-service: default
    target:
      kind: Service
      name: traefik

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
