apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: IngressRoute
      name: grafana
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`grafana.zimmermann.phd`)

  - target:
      kind: Certificate
      name: grafana-tls-cert
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: grafana.zimmermann.phd

  - target:
      kind: Deployment
      name: grafana
      namespace: grafana
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: grafana-image-renderer
      namespace: grafana
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: HorizontalPodAutoscaler
      name: grafana
      namespace: grafana
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: grafana
        namespace: grafana

  - target:
      kind: HorizontalPodAutoscaler
      name: grafana-image-renderer
      namespace: grafana
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: grafana-image-renderer
        namespace: grafana
