apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus
resources:
  - ./namespace.yaml

helmCharts:
  - name: prometheus-operator-crds
    repo: oci://ghcr.io/prometheus-community/charts
    releaseName: prometheus-crds
    version: 18.0.1
    namespace: prometheus
    includeCRDs: true

labels:
  - includeSelectors: false
    pairs:
      homelab.component: prometheus-crds

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"
  argocd.argoproj.io/compare-options: ServerSideDiff=true
  argocd.argoproj.io/sync-options: ServerSideApply=true
