---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool

metadata:
  name: default-bgp-ip-pool
spec:
  blocks:
    - start: 192.168.10.10
      stop: 192.168.10.254
  serviceSelector:
    matchLabels:
      bgp.cilium.io/ip-pool: default
