apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool

metadata:
  name: default-bgp-ip-pool
spec:
  blocks:
    - cidr: PLACEHOLDER
  serviceSelector:
    matchLabels:
      bgp.cilium.io/ip-pool: default
