apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig

metadata:
  name: peer-config
spec:
  authSecretRef: cilium-unifi-bgp-credentials
  gracefulRestart:
    enabled: true
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.cilium.io/advertise: loadbalancer-services
