apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: hubble-tls-cert
  namespace: cilium
spec:
  secretName: hubble-tls-cert
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - PLACEHOLDER
