apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: hubble
  namespace: cilium
  annotations:
    external-dns.alpha.kubernetes.io/target: hubble.zimmermann.sh
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hubble.zimmermann.sh`)
      priority: 10
      services:
        - kind: Service
          name: hubble-ui
          port: 80
  tls:
    secretName: hubble-tls-cert
