---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cilium
resources:
  - ./certificate.yaml
  - ./ingressroute.yaml
  - ./sealedsecret.yaml
  - ./bgp-cluster-config.yaml
  - ./bgp-peer-config.yaml
  - ./bgp-advertisement.yaml
  - ./bgp-lb-ip-pool.yaml
  - ./namespace.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    releaseName: cilium
    version: 1.18.5
    valuesFile: values.yaml
    includeCRDs: true
    namespace: cilium

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
