apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cilium
resources:
  - ./certificate.yaml
  - ./ingressroute.yaml
  - ./sealed-secret.yaml
  - ./bgp-cluster-config.yaml
  - ./bgp-peer-config.yaml
  - ./bgp-advertisement.yaml
  - ./bgp-lb-ip-pool.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
