apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cilium
resources:
  - ./certificate.yaml
  - ./ingress-route.yaml
  - ./sealed-secret.yaml
  - ./bgp-cluster-config.yaml
  - ./bgp-peer-config.yaml
  - ./bgp-advertisement.yaml
  - ./bgp-lb-ip-pool.yaml

labels:
  - includeSelectors: false
    pairs:
      homelab.component: cilium

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
  argocd.argoproj.io/compare-options: ServerSideDiff=true
  argocd.argoproj.io/sync-options: ServerSideApply=true
