---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: bgp-peer-password
  namespace: cilium
spec:
  encryptedData:
    password: AgBXNN7Wg6lz6ywa8qEpLjkQBqP7PKf6twGxqg0Xz3rYR+5VYtXj1h61D6Zw9QJnyBr7n6/jF4gSxv/qyyI58XDq4sPxmMDjhmUlQBI6SJElWFGiN+V9xJ5M7DRYCOdiRb5QB3ettRKI6seueoqKwQNnh/cn4cdTujTa7inOAw9i8TdkPENqUNGVlLrWBS0YDFiMJOssNM8J6JotEEEXXjtXg9E3LhLjWXkOn7DC7Gv0FWJ4YeYpHWmgi71QWd4OiUzHTbOQZ21QwPidD10eFTya+GGvg39qMIX9A0ApvnktSTWPI38ikRBnG2R2wWLzQEqequGrmUR5+PyfmFKzHqzYh6MxFaPUL52aPzobYUulre/SfI68bk0zx4WoI4C7sF+nHTDEvCPilzxnQm1VbgFLz+WkmWqm18q/jFeErmsTS5EGsTFMlcDpGymLscJ2Ngv682LAO2bRLOQ1fnxnrfJs59RnFMVSMi3cLD4yRJ9gsPJwcT6t91muEFJm2+26uentnatS0VTVLGFvzA0OuR8xbdkDBFJfR+BFxzCpv4Sx3Bnyl2wAPphxKfiA6G7cJv2u3h4ietNsEoGkT2b9hFvgYuYZHwiFvmRrkTugk8Riymvvurh764zOgKJujWPYGzApuSqTjSgHqDWkrguW7MCI3hGsEvRMdqkOXNJDPg4H5AH+/okPNnVS4Vmn3UdjG28bxofmybBoHDXiwSOxkpVrP1ZYyA==
  template:
    metadata:
      name: bgp-peer-password
      namespace: cilium
