---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bgp-peer-password
  namespace: cilium-secrets
spec:
  encryptedData:
    password: AgBztWgO8UHnaOUyHSBVPR5CdRzOQQSEnUanY2DDUhcWKTwM0Si4zP3NSPTjv/LSbbRP6Ob1fX1OuXGRNXA29IzjKPcQXd14iRhCL9d7LZzTCtzBkSRBfZnnwvhoC/DnGS3ma9bKeFw7zzA892gOpl0eLrqOsSL1XLxjEEWSUevMrARoWcViVfr7PnmhfdZHHACpf7pJmNnRLica4dUCi/AqFpHJz/DX1XKYbXJ0Au4p2/TU/yfFFgCiKeKt6/yzTdA+tDR10N0OHaTpNWnoz1z52bMuzYmXd24iJVjTMEwrjlcNnjtmOvbc/op6zisiZUQApEwTtcQuaXbMmdDw2uVsy+tz+Qoj+JrlolbPQdmli08cNYkNvO6DwaJ+cRfqwkpIMwmMyQ8zJuhoIsn2lFX9BHjkhoKY4lN3an0FFzEdHVf8bximeaI1/+XuYRVspmOfqQ0/X6dmPopd8yPKFwlRhMBdpNnxlYbF2aLoeD38zJgxxAYvJK3FU8bPCUZtd9vbkp1RKk1M00mMn8T62rptb25x4lhwnzcqQp//YuEtMAEWXGJiK7XeYI7AXoyps09w9xSLTeg2I2T1UZa1WWtTBzXbX8yP7um2iTbsVOhoKcPYbZ6QWAysS7tE85ubnmqQU2cFQJsLSWEA6yxzLkCqRs34VCnMDC715CAlH10lRFrg4r8BCnQPuuoueLdK+E06MPdY53Sb8peD7FnQ6miXN/9zJA==
  template:
    metadata:
      name: bgp-peer-password
      namespace: cilium-secrets
