---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cilium-unifi-bgp-credentials
  namespace: cilium
spec:
  encryptedData:
    password: AgB2rwRzkAFhklWjre51dIrVpmgOi+7Afo6E/+VuAZTkcGZvtF2Qjfi/8DFvb2wHCL+z10nR8SJ/Aivy43Lz9XfGZcbfVceRQ+uhhB1gWxdIE5UtTlUz2HZYjNbXP7wiZV0+9gDcNbjOkC3wHQ3g4CfdXPrYcBmEEVHjD88/g15vEG8KfxRSp3XlsG0v0iM4+/huT3gElHnXIugvHcqkFL9WXJew4dh/a9SbyIFpRcbXWQEhsH9S079aXjNvpQRIpu42WaU5dzw1FFa/WCm9SBwXTbRsnlT+qrmtDye4nLi3fYFYrEVmDh3JQ2bYUOeaORO/I65k5qWFz+ksvrcW8x0MPggJLmXH2CGIwuSXBzmqRF35wkFbadpfP/fT7AiTEJnloV8rNJKa76C61Cm4Z8s63ZKNIceqyNHnVGCW67XlrngOBP3eoMqqHI4YR49kXlwDK/DLKv9XyKMkcc4iq36N83jJqLEvRIDo7S3HuiJExAsh8cII9Is6ehVMhbDOg4x7xQFnCI4JYx+3Iy3sW2P404RrxU4VMwNFvvTQbGz8BXgBkV7YqORjkjWIxEAlqccV/m3niLVDJjoZkiWw+GL5la6DzyDE2kcSR5z0puTYi+BB1CmG2s4KbjEC5s8w+CXsx9P+bYKjTseTebBbKdpRL8KA/hGbRe4AlHL9pe+JD96o9rBKEZEv9r4pOOXDl0gO1MCYd5YJfgYU7F06nkd6thr56w==
  template:
    metadata:
      name: cilium-unifi-bgp-credentials
      namespace: cilium
    type: Opaque
