apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: cilium-unifi-bgp-credentials
  namespace: cilium
spec:
  encryptedData:
    password: AgDAAQNFde/Jl3Yzy7Yx3CnrLKd391wenw0eidTNAPwXQqs/4iZWbkBcoWa+5jdRfxKCPz8sbF7BrR1oxFRfQQgUANxV5rd5jt5+SVXg9zcfK7z6cNsIpmqbVA9P9yKzRcD2XfOVb5TtB5DYFqskXJNaVYGtYMhyrFn7r/4KMM10Gx4Na55hYi1c8hlR0UjzPMMsQf/9dXLTMZxxm11s8B/p5YjUWiRqJBEYE74DAwr+NsSVFdH2SAoSvS+Ail7f7pKOyTent3nUqzA1AbklHHXpCDGmnkR6t9/ASfjntQOhgcz9RniqSULJlv1wS6ziohhOdTnufkI+c8AXVxhW5OTil+8Ymme4F6Bv5gO3CyUT78ntUJoml/vLFmVMEj9qI9+KXmOOUGqo8JlsHdeMcIBUc2Jv9OCTNbjuHIjeAryDy0uWSb0DbqnrIuG8PkrnpnhFNm+an+gaGuLxtrKjH0t0AvkKMs4+WUU5k52PaykDEQIDMZ8RF3QM1lzzb/NHEFRQmGLSrbNYWcwIOsUJPI9IHnvr4z+ZEnR6/W40KuOytl2gNWTXh5El4P1wJTzTOX/wmwElEZ0HCUjqVWNssWrTOPe2zl8BWKzqlP2VOooF/ucV1LHQBf1Ottp0DqbYsSPX3+AH3hNtYVzjxoAXcAuOmOcbVd7HqJuTtTvMQNjUAok29I5/LDZEtKG2I7tknOIyxUB/T9F66kQJygq5sVaGVwzVIg==
  template:
    metadata:
      name: cilium-unifi-bgp-credentials
      namespace: cilium
    type: Opaque
