apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bgp-peer-password
  namespace: cilium
spec:
  encryptedData:
    password: AgAaVD/GdSTUv4dzfDBokRoxCLfn7C+6/5p6Hgp/AFCZAIfJdQZ8YQRLnUYMyjBUqknShU3TQq3W16mFSMjPu9oAG9MTT2p7tq/oVqmQQ/2MPe9wpmIoQ8ySBUBtaK3Q4iMAx3KE703WS281eBVs4/dUNGJstdZtJIeTZeWEXw/drI4C7iPWQuHsJu02lPjpQAwKBeODa/H9ykuwt2nZETwdYzTsBnRWTyqFoifuwPNw3SG5oZoX2dhxZDVF8N5h0z9H9RiCvJ1SM/v2E96Dj3ziC8c1JdvtrN9EhfYMAzk16mhOMogv/FHZBHiuPV0nILvbq3J6r/Ck3PzeccQjhePXhJ/TLSMTJkwCZJsB9wY2DlFzaW1U7G9GLDnYCEMZzYObTUZ8VsFJ6E+IE/iPVmm+8FSC2vYjiagM+o6RCzGUmpGnSVbPdoRWjSrjB6WKHpYsszI5/8vwIor8GJL4wfxK7SO2L8rwZ3rCbjnrN7xagC/+qMdnzXtoCCoY31MajnrcoBeqOkhwNDhehOAcfMhyIDyXv7/8nIdxYawS9P86v75kajNcBySU/frL5UhzzLYY5ZHdXi8dZgTG8M6p9rjiZXkgg0doS/TTX/ArdxsXWreNRjm7Yj/o4IC9lwqW+EK7lt7PvjCQbaWM86WEr5TWR73cD9b42vQL4xCDMogN9lkOsGPNoPyzwSzMcj8Q9Qjodau/vW7HWL+qeaih9IqAJyJC4A==
  template:
    metadata:
      name: bgp-peer-password
      namespace: cilium
