apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # BGP Pool Patch (CIDR)
  - patch: |-
      - op: replace
        path: /spec/blocks/0/cidr
        value: 192.168.11.0/24
    target:
      kind: CiliumLoadBalancerIPPool
      name: default-bgp-ip-pool
