apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reflector
resources:
  - ./namespace.yaml

helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    releaseName: reflector
    version: 9.1.45
    valuesFile: values.yaml
    namespace: reflector

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
