apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject the desired replica count into the embedded StorageClass YAML string
  - sourceValue: "2"
    targets:
      - select:
          kind: ConfigMap
          name: longhorn-storageclass
        fieldPaths:
          - 'data.storageclass\.yaml.parameters.numberOfReplicas'

  # Inject the Reclaim Policy into the embedded StorageClass YAML string
  - sourceValue: "Retain"
    targets:
      - select:
          kind: ConfigMap
          name: longhorn-storageclass
        fieldPaths:
          - 'data.storageclass\.yaml.reclaimPolicy'

  # Inject the domain name into the Certificate and IngressRoute
  - sourceValue: longhorn.zimmermann.sh
    targets:
      - select:
          kind: Certificate
          name: longhorn-ui-tls
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: longhorn-ui
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1

patches:
  # Longhorn Manager resources
  - target:
      kind: DaemonSet
      name: longhorn-manager
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: longhorn-manager
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi

      - op: test
        path: /spec/template/spec/containers/1/name
        value: pre-pull-share-manager-image
      - op: add
        path: /spec/template/spec/containers/1/resources
        value:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi

  # Longhorn UI resources
  - target:
      kind: Deployment
      name: longhorn-ui
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: longhorn-ui
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi

  # Longhorn Driver Deployer resources
  - target:
      kind: Deployment
      name: longhorn-driver-deployer
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: longhorn-driver-deployer
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
