apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns
resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml

helmCharts:
  - name: external-dns-chart
    repo: oci://ghcr.io/alexander-zimmermann/charts
    releaseName: external-dns
    version: 1.20.0
    valuesFile: values.yaml
    namespace: external-dns
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1

labels:
  - includeSelectors: false
    pairs:
      homelab.component: external-dns

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
