apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: external-dns-cf-credentials
  namespace: external-dns
spec:
  encryptedData:
    cf-api-token: AgAMIybTJFoaLtHzrrglSzXVdSkzFH/Ok1ecC4pAD/aGwFqiXfI+i3ZQHdn+ot6wb7AVLJpA+ItUevpfuxfp0dQVavGPvuI5xirINsYC960LQLXiScJOhRmMNDwVWKL6gT86dyfqLRfDmQ61ETJfH4AmMMT5pwm3nY9cBB93DwYLsPPjZtgpZF5qTDBC/esQu+vgkDsvpYkr+V0FTaZQilQARCXwDReyzoQ/whwhPgSNopLiCtB0g0sZAafBOtVUkFdbqk1qyKYUIYPBizbrQS3qi4sIs89m3N3dajX0LU3vdP32uGZNk24QwlK/fDAnA4+/Yo7h7jc6mvVqVv+KMuKE+bZ3yI7Xc05Hrva3mVJxVGPjxM8etnhblV7fUHndHZu2p8JSfxUtIwrOGEig8dRTCBV5h4xtzyIRJGoaC/1exKh1FIj0z7rhavK/bVoKCTuLUa69tcNgXVqJOkhivnEuEL8W0Cshvuvqq1szEweXw9x1csDwtxq67ieK1UZZZrmeX9uY4qlACu9PBU/6qD894jgKYsMvHUG73MqnSi0oLS+4wDTi8S6vhGFjfU0KxEw5529O2OZIhxeiG/cbIfywKVLZxLeRNO7qfIui3cxHdZOWTP50VdaQAZzdC6I2ZRhQ/uk+SygNdwq/CvXcJjod6lcJ3cozHXJcBV8kZBFKC0GtXOY6jU5rmzc52Wz/G/2S8W1nbZL8of/Oh/TzmJZEs0iCxBSIsyAFVaXDjozyndAW++FWS1mX
  template:
    metadata:
      name: external-dns-cf-credentials
      namespace: external-dns
    type: Opaque
