apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: external-dns-cf-credentials
  namespace: external-dns
spec:
  encryptedData:
    cf-api-token: AgCKngcXsHanzdjLzUp/+5wTUSevl5CYQrQn6sYkKjydLXPXqv2V+ooXsYpv6LuXJsNAiRSrpe9b9e4yezl13usDxXFhrW6z+Zrpk0m0nLLI5/jRonYlozTzkXpRHzpC/yAyKHSOy2H4h7JLIILzzYewm7Su0xACiksUWyktukZlhyMDuDR96JCfVNXirKNXvD9bZyWVT6P35B5VYvlzEapC3k1rXe/WBJs7yVCkoLtyWzYGRv1MYmjJF3A8E1Zd4Wx27ITUZJJ9E/QQAy38gLxfY2SQWEpAola5WvAk4eCOwv/VtVOM6SNufW5rshl258NoDQZ1nK0IF/HrYvTv0BuejcnYXXXEc+pdSj5ETi71afSxfXASdt+OXnfPQ7BCRvMoPfdaZ4GxiEsTr9ecAZMuoj5x4NeD5yS2TrTm71cShgqPTRGeI1r5wAtE1RboiMsY1vce5TpvyjF3hqOaT98xwX1uZc0PL/HzO07NjErAOV61NcGloEdlbkzDJRu2w3EPT0LmgDTSKlAde5g4n8FztbDDe7zukbl4O+EUQPH6ktYyKiyc4mTNkjX7E2ItsPpGKq//c/vhy0YTZVg9OqPn4bqkPWfgY9o30te8Ov28NHRmDGGzqmB9uIIWusr5m85bqY1iniT5zoWiptV+HIZcxd8t6rbnFGqOQgwmGqDVIVP4ALTSXvHJXin+JanHiSZNoHN82tMIFhOv4RC6L7R0zoT70w+ALlhohnMgEgvXcPOQ7ToFtl1a
  template:
    metadata:
      name: external-dns-cf-credentials
      namespace: external-dns
    type: Opaque
