apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # StorageClass: Single Replica (No Redundancy) & Delete Policy (Cleanup on PVC deletion)
  - target:
      kind: StorageClass
      name: longhorn
    patch: |-
      - op: replace
        path: /parameters/numberOfReplicas
        value: "1"

      - op: replace
        path: /reclaimPolicy
        value: Delete

  # CSI Attacher / CSI Provisioner / CSI Resizer / CSI Snapshotter
  - target:
      kind: Deployment
      name: csi-attacher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: csi-provisioner
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: csi-resizer
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: csi-snapshotter
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # Longhorn Manager resources
  - target:
      kind: DaemonSet
      name: longhorn-manager
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: longhorn-manager
      - op: test
        path: /spec/template/spec/containers/1/name
        value: pre-pull-share-manager-image

      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi

      - op: add
        path: /spec/template/spec/containers/1/resources
        value:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi

  # Longhorn UI resources
  - target:
      kind: Deployment
      name: longhorn-ui
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: longhorn-ui

      - op: replace
        path: /spec/replicas
        value: 1

      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi

  # Longhorn Driver Deployer resources
  - target:
      kind: Deployment
      name: longhorn-driver-deployer
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: longhorn-driver-deployer

      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
