apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Set replicas to 1 in dev
  - patch: |-
      - op: replace
        path: /parameters/numberOfReplicas
        value: "1"
    target:
      kind: StorageClass
      name: longhorn
