---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-poller-secret
  namespace: unifi-poller
spec:
  encryptedData:
    unifi-password: AgABNUTNFgIMj1/+5Ar2RXysmPydbdVchZPMQU0eFiEzPDl1KyBFQGGbZFD+GfeekPYdI5iuzpRheuhLcF3v0Xrpp9XeP1KPp2Vmr07zefPtUueqj2BhFyZ8WfLPTIe4wQUdsbhyWHJF831ml6dKARa5p7On9LZZsM7mi0k1+YFU6/TeH6Tm74t9KXOFqg0MEVOUZYJ2XcCJE2AZjzd/X1KrlxKtqByjsr2UU6QB7RauBprRNkrTN+KsC1ZklWvqD9XSUTME7KwnSEkhjrIz7EFyd9qbnC1SCpTW37tt26UHD2qDHIUbOBytyzq29RJeXV+S1eYfqP2V3XKXBDMIeMHmny879nQyItZLV4MJqwRIhcQrMTrNVPuZXmP+hjOhyutGvkR2m+pgCv787uvsVqjroO2NL+cGS7jU0tBALE5HyiLljH2UVjNqSYv+plTx5BLpK6Eyea2fJDderzl3A0jHDjtC4RZssbRyoU/PjY4ktFe2lxrh8kAc/B8PCna5av3bDAkxAv/O+obGyElnTd15y2ixdJ62rzaJfIQohlZkjcV8bIFm7Vn98K2NrWPXW6sBIDWRaho02lQwObTefixsQAftneOo8o8rzGDA3/+zAMqwg5Emq05VjafsX5IiuGI0cUJC/civ6d9dNsI1Zp6F9sVo4kot7InwhexW3lEaak6sl9Zoe//CkBDuyZ0vGVPyoP/iAblEp96VuY8Eq4oaPBUd8Q==
  template:
    metadata:
      name: unifi-poller-secret
      namespace: unifi-poller
    type: Opaque
