---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpoller-unifi-credentials
  namespace: unifi-poller
spec:
  encryptedData:
    unifi-password: AgCMwwmq7XT28aMpWMtL4FoRPibn0HbVoRE9PG1I1Bmr3ai7cjOwayG3gYgXATDKV/2VVBKeXNEWHZzmA9tyi8I+ugGtBbTTfLplpBWM2+PGhVIpPLuHBWbeqM5eqWji1Eb9VCiyOl4ffuTTRvFQ8uSdm39VNdBvmnZUbFNiEckFDEoKetbLhxabisbtH7lwZ7HxhURjRKTyrxQ1J7Kr9IrjdLV2JM91tMyUHwO/DnRnFFPT73kXJ72H7VUN4z6CBvucrogIMnkG6w9Ok8QDGecBpVVvEK6EhoQvbRUBn+/GNZubRe0pet4uLCFjiw3HdxKXHt+ABoRBvqJnl2ts3BJjNWElu+9bybh+LWxOAMMRi5PA3Tr+rWGcZHpd6I49jzfVKXt7OqVP+i5Bz8ke+6/7+MALaqTZMnG1+KfIJjOGrFUiSGBuCeVsdLsFALlKFS6HadmbfOjMNjSFlMVYbLTtZ9s36P/xtvzdquhBzakrbcveH5Wkrw2p2tMfGzySnuehNjvlz22HWltjaN9M1YMgtAvdsUIzoXNAyTilVUcS4QKKWlAWlZC7RHG9v5W2iOXLyBjPouRf7tybBjWe4VLyd+tY2LqqX34IRj1nQl97HDUO4I4cP+PvwwmjGKQEh/m7e5YOerSTvkDMdEYIPBTP+9Rc+fVLZRb2iK9Ub8XlEANToGl3wBbCLBnWaiKABBWAmSfpsdhK9AjigYbW0UgrIPC/AQ==
  template:
    metadata:
      name: unpoller-unifi-credentials
      namespace: unifi-poller
    type: Opaque
