---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpoller-unifi-credentials
  namespace: unifi-poller
spec:
  encryptedData:
    unifi-password: AgAG1eQ1UARj/GfQ9QPj+wJSL6rTXR6juFf3cuk1XbgdfsKCpzg1PF0bVjRONbXxHUegMstbxC2QbptaT2NHau1LmeVUcCZIoH4kLDAdf5Xb02pv9g5POGEA63nQyQ06k4UdWQeO6RVBrOLa+Hj8QgEbdy+6LLAW0tfJQyJkiR770EfGECbO3wNOG4IaXxz69s+tyXM30t2TAiSoH68k/puzw4HqQdJvfpZfxAv+iIWGlMww3KjmlGB53KJ9+RCxIxjuWtfmgrIFLFlmcV6DBBQ94fFmP7Z+YucLtvgEnEOqqOmHhnAI43JbYqxCTASIiOW+OXFjJSk1xWx32huwGmPIntqMnYW0VK0XTxhshGbKj4YXnsaaQN0zQPh0oQt4hdkByf7Xx/NnmwSMal/4MUtrIPiM1xBqqhFP4IdPT3nfHxZz3E8lnM9r4TmL9krcw77Y6ZZ609Skpzk1Wil48t3I0XSRrmKmNUijp81kVvi9gxW3bNQZJccqBXpXbX2108lpo0l+5yhAx86GhvpSbeHc+WqPe9LDPkViDq79NL8OyQvnjKlHfS/iNcP1QEnmlJykuqtQ3lC7ir6UoE9x4qb6Qx8TPiuBoHTPVQeTwuKe1JfRX9r6osENPC3NNlujfC8fS1ypt8t3WB5FMgap/kPybTki3Rg7QFl4oCPByJeGFPLj0KZqNue5gvzWTWsdolhznwV9qOPZ7cDcMiJa8NofteaVdg==
  template:
    metadata:
      name: unpoller-unifi-credentials
      namespace: unifi-poller
    type: Opaque
