apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: unpoller-unifi-credentials
  namespace: unifi-poller
spec:
  encryptedData:
    unifi-password: AgCZ4myk2Dj1xrvtTwBESy/L3to+P5eolaqxaomk8i3R/Up4pY/EU9MQIcnRK4rcPQs2ktbDS37LPZ2CqTO0GTb7X7IqlGqccJ18UF6+6uuguV8UfnJ6s0VSsvD+rsu9MY/cM1TjUN1ajvIX5HYctxj77julVRg4IhBtFrE/pmyDOaBnvm6ZjmqEWZ77nHfG8ZYSwT6ssjQC1R6E+IEpCKDWDT6Dz2fnkp/jQr+eT7RcuVUs2y37XjK14lmSfiCWU98KIDkUZV9851reFOeFiobJHv2YaYzzUgR7vIIZ7HqHvD0GEUPk/+Qw+m8XIzx3AtWbcGeAngQh/TYF4ZTw1a/hZ0xEdu6Z49NbN5T423bio5P13/ydMgGitLySHaUEGYP5fiGY4vcj+qEkytNl95X9cYy1//LymEBMZxTjCbhvPSxhzB7H1S62gnbssD9hCEZAllcHCg/zm+je13e+xpfOVsjkxjFk2OA2Lvw6xtxYmP4NvXX+4ofuxajZXkXn5/abj+bbI9jef2rOGrr1McfB5/Pyc3u2lTuPBDMSt2G9ZvNY30fvjubgU9xPgRtv2ZwUpIKT7g0NqopO5C2mjfmNllu3wtXTzMonQnyx0jtdLJi0/IlUFKFcb7edWj0i4HxWw7QEdYax0MqYMJHSNzNjg7pgyNzJUkRIYQPCnYPgmUf889evUVyi4HpPU9Bmx3rMkPJR9PIkgWGk0h6aslgG9gYm5g==
  template:
    metadata:
      name: unpoller-unifi-credentials
      namespace: unifi-poller
    type: Opaque
