apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: unpoller-unifi-credentials
  namespace: unifi-poller
spec:
  encryptedData:
    unifi-password: AgC18bOmKsVwYI9E6Vex0lrzuw5SUmvwCRYp2TUx2djs2L9bLxLeTEnnkTTyAqDm3GY5ojMKYibozZLxJgV9GB7azvYr5RbKHTQHqQA76/OZJVczaAY4AcLp7doWFQk2Ex0ZfNl9+CVBevTWsz4WDXJ4k8yDv6AZz+FsYLyp0Pkz3lhJ3OWywIjZS0zw4xgjL5fQO3XPZoWlaG37qyLkCskNqA5arIfBoIVF8m8dCs9VVDFJnZRII8NMFG/tANq9CR4MRa14JAW5gx7MJyl0wxZ+tSuGWhrQBgceQ/RD3i0w7JXuRhBftcgoXoUjbbBUN2DklWF8yMFNJPcrb0EOzmbaKrpeAQHYG3wnXo6n3Ykqa0cq0sGoudhLfjgHV4DklU+PH4Azo+6Z3cbN2g3K/hz+SrjvoQfTBw/ZsWBHP8WCok95vVygUJsNBgJG0wgVW+Rur/gBJL39W2JJjkiv5zILW4cDuksxyB2scE+MDhvErkCfmZrpSTb4RN40BtN4SEfUO1gga7IUwDaDeBR3WK4/6FmjzA9yCyxSeepmCuYk3odFSJYvChAYufuQpUf0QnW9qaVi3BShzZ683MynO6Ii4UcujvW00kucF4bzCyvzq2LPnT0nPzlaS1GIYvSgTwUqIq50SH69sYo0Z4K7bHl5FbeY2OVXiLCSCFjJuIocfjXU8w8zQb5EsH5bvnyJXehTCDyjt4OJamHDKEBMopKxoyyW0A==
  template:
    metadata:
      name: unpoller-unifi-credentials
      namespace: unifi-poller
    type: Opaque
