apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-cluster-secrets
  annotations:
    policies.kyverno.io/title: Sync Cluster Secrets
    policies.kyverno.io/category: Secrets
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Synchronizes essential secrets across namespaces to ensure
      dependent services availability.
spec:
  generateExisting: true
  rules:
    - name: sync-dhi-registry-secret
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - sealed-secrets-controller
      generate:
        apiVersion: v1
        kind: Secret
        name: dhi-registry-secret
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: sealed-secrets-controller
          name: dhi-registry-secret
