apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-cluster-secrets
  annotations:
    policies.kyverno.io/title: Sync Cluster Secrets
    policies.kyverno.io/category: Secrets
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Synchronizes essential secrets (e.g. rustfs access, grafana credentials)
      across namespaces to ensure dependent services availability.
spec:
  generateExisting: true
  rules:
    - name: clone-secret-to-mimir
      match:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - mimir
      generate:
        apiVersion: v1
        kind: Secret
        name: rustfs-secret
        namespace: mimir
        synchronize: true
        clone:
          namespace: rustfs
          name: rustfs-secret

    - name: clone-secret-to-loki
      match:
        any:
          - resources:
              kinds:
                - Namespace
              names:
                - loki
      generate:
        apiVersion: v1
        kind: Secret
        name: rustfs-secret
        namespace: loki
        synchronize: true
        clone:
          namespace: rustfs
          name: rustfs-secret
