apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: admission-controller
resources:
  - ./namespace.yaml
  - ./clusterpolicy-secrets.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    releaseName: kyverno
    namespace: admission-controller
    version: 3.3.4
    includeCRDs: true
    valuesFile: values.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
  argocd.argoproj.io/compare-options: ServerSideDiff=true
  argocd.argoproj.io/sync-options: ServerSideApply=true
