apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: kyverno:manage-secrets
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: kyverno:manage-secrets
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:manage-secrets
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: admission-controller
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: admission-controller
