apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: grafana-tls-cert
spec:
  secretName: grafana-tls-cert
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.zimmermann.sh
