apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana
resources:
  - ./namespace.yaml
  - ./certificate.yaml
  - ./ingressroute.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    version: 10.4.0
    valuesFile: values.yaml
    includeCRDs: true
    namespace: grafana

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: grafana

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
