apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: longhorn-ui-tls
  namespace: csi-block-storage-controller
spec:
  secretName: longhorn-ui-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - PLACEHOLDER
