apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: csi-block-storage-controller
resources:
  - ./namespace.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    version: 1.11.0
    valuesFile: values.yaml
    namespace: csi-block-storage-controller
    includeCRDs: true

labels:
  - includeSelectors: false
    pairs:
      homelab.component: csi-block-storage-controller

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
