apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system
resources:
  - ./namespace.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    version: 1.10.1
    valuesFile: values.yaml
    includeCRDs: true
    namespace: longhorn-system

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: longhorn

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
