apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../../bootstrap/cilium/overlays/prod/

replacements:
  # Inject domain name into the Certificate and IngressRoute
  - sourceValue: hubble.zimmermann.sh
    targets:
      - select:
          kind: Certificate
          name: hubble-tls-cert
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: hubble
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1

  # Inject BGP IP Pool CIDR
  - sourceValue: 192.168.10.0/24
    targets:
      - select:
          kind: CiliumLoadBalancerIPPool
          name: default-bgp-ip-pool
        fieldPaths:
          - spec.blocks.0.cidr
