apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml
  - ./cluster-issuer.yaml
  - ./kyverno-defaults.yaml

helmCharts:
  - name: cert-manager-chart
    repo: oci://ghcr.io/alexander-zimmermann/charts
    releaseName: cert-manager
    version: 1.19.4
    valuesFile: values.yaml
    namespace: cert-manager
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1

patches:
  # https://github.com/cert-manager/cert-manager/pull/6192
  - patch: |-
      - op: test
        path: /metadata/labels/app.kubernetes.io~1instance
        value: cert-manager

      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
    target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager

labels:
  - includeSelectors: false
    pairs:
      homelab.component: cert-manager

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-3"
  argocd.argoproj.io/compare-options: ServerSideDiff=true
  argocd.argoproj.io/sync-options: ServerSideApply=true
