apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-unified
  namespace: cert-manager
spec:
  podSelector: {} # Applies to all pods in the namespace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {} # Allow all ingress traffic
  egress:
    - {} # Allow all egress traffic
