apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-unified
  namespace: cert-manager
spec:
  podSelector: {} # Applies to all pods in the namespace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {} # Allow internal traffic within namespace
    - ports:
        - port: 9402 # Metrics
        - port: 9443 # Webhook
  egress:
    - {} # Allow all egress traffic
