---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-cert-manager
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBvEcLRB+8Yt1CbFjaNDpEN/cB8d3cTr/c9CzJlkaH8kIgpduycEHmZ/8Mhk6+dOXSDpKwimxmslbDLwWOpJj0ZFUXLJgzgIk6jzr3+Cu+WZmAJDmmt8ZuK2GF1yvGg0/grtY4O+IEZlrpsEM9SjbR6BSsa8JMo0BfRLASMoVjLKtVD2XZFNduxLMGeoNbjaKcQxnhtqnqbMSNecZKCDXzbsGk1cr4C0TI1P6TTG8dqDcKBWx2JcFHORg6mAJhyCYqBt3b3cVm5X0x4h2MCg3ERaaQ3q30GxGqAz/KG0bu9FEyPBTwNhPdRg6KXcP21CWXLqRtkHgTZ9FkxFJ5ZsfWaDPGA9sbXAc/gKhIR0L8kneh065e6da4BsDs+nbPnm2nGaZDu0OjunyoGoBfhfIxN6YJNrzWklY6+gMtt21bugGP1r2SWd6GF6j/a6whwYV8E4H87wg8CUOi5bKKD1jR9yKDCunMCkfYipHRtG0XB1imeUBXLuT1apnPFauAyNUavQ9qmPNGnCy3L3QSwvCWzcE1DLEwV81dUBX9RVoob6boO3JnxlwlDzM0xxYVU3dGbCe/CD5pndfk+Z55RJ42/ue90W//22jjfexoWXByGJuNIikY4uyUFsgZqfDjaTbdLj7MjaPaHV41iNhlfRNR9uEfKZwKEmxgxsXTFILA94+w/E3uXtn4ffpvLZk3OPqy0xM3ItrqYJ+Z7bjRQczf0wMWq8UUdxCUrzGkVkm7LvNAPtw6HojHO
  template:
    metadata:
      name: cloudflare-api-token-cert-manager
      namespace: cert-manager
