---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: cloudflare-api-token-cert-manager
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgADmSIcZQ9BtqTQcX8G2wA6FVZIm0DeOjZyIMTCboDlHvbYUwkkDYeFMOtPnW3EjDYg9VNwlPFsWs8dDnbCBUqPBwIgO2vQWLjkaieelmp6iW8hvM1LZYs5BwRanyBlSBB2Dy+U6HvKD54yM/mvXEFE72Eibfi3p5UmOoGBcUzICpiPBJDVU7k10298zCcK+aCbsuPw8uSq6ejz8opLZc1l0lGLGa0KmUGldN+WLtD6QSCvSiWGf7T5MIuBetX8oCvDrDgAUEe9HQxlfzxYcM8DXIZq8IxoUYI3RSVZfKnLVbhBjXnebAE3e8OxDYkwtF/shkOlrAhAWusjxoUoSJ/nnhKSBfFn7ZoE88LLQjQqQca4ItBUoXHr9H4IxRT2SrotiMhQz/gVuIDnLxXEhlUfRzS2R6VAh4F9WEDu6DnH9ZTJcwb8RledETSvTMh9XGvZe79qa5ssga++3y9zxZYZ4LMTp9f8Sfc9RvrSG8MMa7Inafmaqvthynib27MUsSjz6zN7Da7S9eP8vFDJIwXlUE16xbnGMS9nFXFc5Krsr/CYKAmQwn6PJR2I/OqMpuGwtaOotibjC9Emtdfyf5Qh3RHHRGdiPHmnOL81q45qROsU9OIzr//3ScltBZn61epl1kVXYPdYrvoApQzbvQ5VVhLHhiD89nmhn1LOc7r8u4St8vVxpsKDaE5t2wbc5RIZn1hZYpsBgwHQd/i0W7J0AmOfCH9OdI1LVlmTR9okG+x88M8C4nSO
  template:
    metadata:
      name: cloudflare-api-token-cert-manager
      namespace: cert-manager
