---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-cf-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAHQIo/k5btnKr1hnkKxWHmECvNFaTtCpmW6YDgXZvPfjZUZ1dYZu3SVCtCGtGZdacu3SToxjxZU4IXzQ4A6hHO9J57rSnQk/NTA5kEqlYKpqjthPi4n1Ev3PkuBIfrw5oaVZY/KE7g4KRxOnk3Z1iCxIczpEorNaBRWmG4TWkP5mnkJXV7pgy+8rb55GihZcrPc5L8dPa9ONUt03Bjx0E1LMDcn8t3EkzWSsXYeRsx1GwYnQFvom9iExo7RftWcQmHeXptJNGRoY9ucmZrgm2hCHGUWB2t6R8TsO1Ph24cNvm3Xn9E8MPU0TPwUGIZL79B0RtkMYsv8uKxF4kqOnJE3hc5odLt57PyMCJOplMbKiUuTGNkiNb1frEctmJAoq1UjsEO2ejr9G3Hruvi4foQVQ6OqwdFHI6p+1Pvz/9qKW6YIFg1kLKe7mItXzToqv8WtgK12xLsyCM0oqfGNS8aAeF+cV2hpPZQHceC0beBs/6IvLvn+I3GZ6EY5ESL75hCUuDNwF3C3/pst68TqIFPYt9ibAYkCjC7KVDZUQngTjTH6hRqXcay4qRZwDB1tqq5LnKWl5Y7nn8ajc/zjQ7PIV9QLq9Q6eIi4Ir6D2tJh28r4gej/lvuyF6PhfiFu1KL8bGeOkwITmbgfzq1gZUiC0KgAsVp7aJPMLxChAvwWL5QTUk7FfKWYk41TacFzOVlYAOq6lCkQsoo43zhMmCD2GAhrLQMIOEh9IwWU7jkFZMEbcft0d81
  template:
    metadata:
      name: cert-manager-cf-credentials
      namespace: cert-manager
    type: Opaque
