apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: cert-manager-cf-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB/WTc8XZjdFXNMgwTfK1e3Gbx+5eVFTmjwl0Wd8nWzUim89o/kD5SA0t70o0bTHOqAM/AZHTJbFPoI7rajaHx0K5ILbiGDbMkFYpzKPWNSeYURO1VBdn90Och0NPX1Uy5SfBjy0jzC3eqRWzEUHyMJAHNMJN3Gv7QTHluCl0UVh82uoleTbvcQ93SUEHANfUUoCZO/NBQIGFebOKF2bjMXL4IfrQkL9BFSqpx1fokEtbXh8KcB3KQKJxMW/LdactztRL6eubFW1LMlfXKhD//AOyxANNM/xSv09Uv03w7D/s6kH8M7eDkLxpb3ytzaSE+cW/BZPSBkIlKlYLU//o14Ktvs9DbLRrMn7EaD8ZF2UuYGbyotzyqhgEFmoXGEit9pa5m3d+ksmUSJbm/7veY8NTzlYL24ntTwKpPnUsBv+fkNC8iqUdjK+Gq2e6gwj0WG0Zi6MIY4oKhcMvp9MWdW/jAxt01TKhfunjDa3dN4VeoLzL1mxKzDozVpNdy2LTa/jSImM/JaEOpb7/mN4vongIyW6eQ3/v4BRxWtUV7rVn3glfgPrHn0TCEWWl1DF7RElr+RhGwvtl0l6dkL3rHhbZ/q4C/b2oUw2iln8V9X6jNmfHUsrHC+++kRvyverTbGg/08XyEO5WbW0b3Ss93I6ygSMn02RLOKh/3OKoLnuzyZ66Ch2e5/L0g3Z+OA11RVVRvbdQ44YaSzhHI62RbK8UJ0xabvUMnqwMdCABW0dv8VBzQm6/wL
  template:
    metadata:
      name: cert-manager-cf-credentials
      namespace: cert-manager
    type: Opaque
