---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: talos-cloud-controller-manager
    repo: oci://ghcr.io/siderolabs/charts
    releaseName: talos-cloud-controller-manager
    version: 1.9.0
    valuesFile: values.yaml
    includeCRDs: true
    namespace: kube-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"
