---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: talos-cloud-controller-manager
    repo: https://siderolabs.github.io/talos-cloud-controller-manager
    releaseName: talos-cloud-controller-manager
    version: 1.9.0 # Matching Talos 1.9
    valuesFile: values.yaml
    includeCRDs: true
    namespace: kube-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"
