---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: talos-cloud-controller-manager
    repo: https://siderolabs.github.io/talos-cloud-controller-manager
    releaseName: talos-cloud-controller-manager
    version: 1.8.1 # Latest stable compatible with Talos v1.9/v1.8
    valuesFile: values.yaml
    includeCRDs: true
    namespace: kube-system
