apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki
resources:
  - ./namespace.yaml

helmCharts:
  - name: loki
    repo: oci://ghcr.io/grafana/helm-charts
    version: 6.49.0
    releaseName: loki
    namespace: loki
    valuesFile: values.yaml
