apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki
resources:
  - ./namespace.yaml

helmCharts:
  - name: loki
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: loki
    version: 6.51.0
    valuesFile: values.yaml
    namespace: loki

labels:
  - includeSelectors: false
    pairs:
      homelab.app: loki

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
  argocd.argoproj.io/compare-options: IgnoreExtraneous

patches:
  - target:
      kind: StatefulSet
      name: loki
    patch: |-
      - op: add
        path: /metadata/labels/homelab.app
        value: loki
