apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki
resources:
  - ./namespace.yaml
  - ./sealedsecret.yaml
  - ./job-setup-rustfs.yaml

helmCharts:
  - name: loki
    repo: oci://ghcr.io/grafana/helm-charts
    version: 6.49.0
    releaseName: loki
    namespace: loki
    valuesFile: values.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: loki

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
