apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: loki-s3-key
  namespace: loki
spec:
  encryptedData:
    access-key-id: AgBjziO4lMe8wpLsLpgKz3ai65V4V0KMK1aIAgDJYx06aPavQNgdEJ6K7B48Qgqc8lfWK6cT/6pNUCuYL6x9IH1VfIBhBIMeP5tJFtv1tx9cZ0RF/RmtBCdbvA+PEcE8dUkKv1ht+ungusTDkrh2i8GltUTzoDWBRN/cjudr4iKhw8LDAEDaeh2K7JnpUJa4n7AU2K6er8+sUeYStEIQ+KJz+XQhsziGmbBNIreFpB3ouYKJ03kHTKSr9h6i3wfylX7mx67ZtZqfUJzRzA1BrNLDjiWFFevL8SE/tz/2CHj8mzTE6M7CnpABiWB1mZGLeqjUu/Jp8GsT3XFX63TsWmjYynyaEjLktuvj/h/uAKokuELmLOP+xgfSANj2CrtS26XA2fAe70/FUtD/Dl76QO8vELz66FqNdhYeeKavpI9RvVtLXoR0IZasco3WDXCDoj5HUHeKwKRDaIt2SAazVrZv91dYfP3NbeSt3FmfcgtAXlVa9MJaQ72blXKFCsdpRhXmTBGAeLeQPeCaf8qadxSwsB5sgyG3uBdJfNug2zgY/lb/7Y+aaU1/8a36yUj463V9AKmmp/+ICMpqgm6bH9KW88VkOUAaA/EchdU412tVlVEr5AvI/B9pWLCRu+fMrB6QG0Dty0rUrvWxy755o67WZHmH27U3BfhDTT5xQjlKJeVMEMyJtab+FnvfhRfrEVCEQsNJ
    secret-access-key: AgAZ7+rmXCvvlDiBdc54E90nlYNMSz1Ynkmlrhqw+tzRM1oUycSwhezJ8sYcRX1SRe9lVbxzVVZfCjJPL36YosMLYQL05Sd5aQBLcVC8yBS54SvpDwtUtsgDFVoRrfuXpTiFdqdQoYN5dQhw8GF1fc2gJHFLU+kq2CRw2Savz5KyS/Q11gUE4t4uQ53oQcH6MWIYfid80flKO5eg0JlsvvkOFu7Jz0iNPIXGR4BzrShsE4lOFkR+J7Se9qovZGzApKe/81r/NKi5sSZZHPeHLWqtprYJmyEa7BVmVe0vCnU4h22xN6bYdpJgTW8hS+MX5U428aYa616Vt3RRLyewep0pfL7VP+z7+q0X5Kz+x23SQ2dCzMH6U4jHfxgNyj6CuEuHFTOHlDy1ospOve/tGLa6idXDcXYC+n0QMNNnhPVjLSl7qbj00LS71woLRcSoVCsoqWRZvqDM1ixBH+OW3k8YGLC4SJjNiBBap7jSpnxswIORVvZDmZXPc8IerPbNVo9G5Dc9h6+BJFnNApcvZLeTMKDjsriD2wB9ukh+EswcUXbb9c8A/cJmR6X/N2EMeOjf0AMX4Vhtw5/JxzRCgtarhHpRBFjpp1AENtG3+AmCPqtc8m7dtG9pQkdhdSjYnoBi0NozjLDG27uvqFrbDwzvi2rqjSgICV24urmJX0xypX/g2pYcvdeXI1NGaGXCffTwzUWRchlvXlYhvW8KMCyKaNifSqCqOT0o69nst1t9k8p4
  template:
    metadata:
      name: loki-s3-key
      namespace: loki
    type: Opaque
