apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: loki-s3-token
  namespace: loki
spec:
  encryptedData:
    access-key-id: AgAOjrBdfd2PEMPbnz8DU7kzUjIPV4mHuwaVfeZFEBOyH5/gBdJKXyRn6YBbZYUEFAxROEwqV8nehs9wzrHFXvk0DdrEg8g1NtZJHvAag6X7dh96NiaSghTRN7Ej1VJigzUHlG730PB9FsKoc+2BLDnvbRIlI2EE4JyVKkP3royJdwHnp09YlsaIN8lP752DsIQ3K2YpKIxDOAEFryDlDvIXfhPx/WMmNp57XImG+XaODiYEUIxIqfA49+Fb+4cfG+kep6VVerfHH5oN6IHSIw9NeZqvpPpRtOgdrrpmK7NbAMQnoen7B/e9oO0xFyg7Xr/clr9AM4F1b3pMoWzoepSYHjKwMTn+iL695OzJqq5h+nTKHc8kLMOraimL/CZRES33Fi+dwfjETHhuMyHKPKSj9XimgsVTM15Zlztun/KVkfu4CjYNR+B92xGYIdENyDRt4sLG2+I2fgadNPiy7ilsECRfBm1iXKCFL/mFM6aKG1yvTZF95NHtBWsVx3gBtwdbQScYSYugrCSMiUfKslgvrybmrtGwUOZPAIg4UXj+VHnv3XlKE5tJi1Mv7+Gj49ZqmMfixzyxi1tnBbi9kHEdZdF726NNT6t0SO4d9o2OASV/YgJLmA+zgVz5yoJWaHLtsyyZbZGZ8maf/u6FXIBQNo95Os5CRs8GrjWTGIrZbraR7LoIySOSpMxDG5U0dL29Y7eF
    secret-access-key: AgA/QOlf8QH435H08Q1zAxqb2ZMBimnK+q3XctE+V91442HQiJzliHZtoYjZ4/gQTw0mvz4aKrk14rO/dC/F0OqoIhVbrOo7M+XEhQA1/3Sr72O4eXzqChoPX8mv9f02fz6Ov1Db0Yf3PGX6x8TEXEd7I2ib0vDVpTjE80TmDLPwLs0ELUEbR2MV3zcXdNrONlUGdHldqlLi/E1T1W4YLZJdX7oBcbe2mO8Bg6lBrWdobjGRpi+Prg4PaCUnn31VppdRU2OaV3LqYdNpCVD5vQDO+tKoK0SfJiLHjou2v8iPHDAtKwnH+aQeG2wPwTO4h6bUoVQ7NA2Slxz/EceAPSstNGYM6w6uYKbQvU3XQ7q9HNVCUQo1EViYHLt4jKulYhjAzlPnih4iQb/LZzBa0HPRK/1w4OhYVELIqG8PeLos1iHi0HbGzcIGDwKXUF8W7bN5dsAiDbsUXtK2BGOkwtBw8JqmjlilSqgpmvE43oQrtw2biQYWG/Kd338Sn3CwclMSicix9cG9B4wmDy2ed6B/0leb7k/i+IsJOLDWKRP3yEfgJxnzXrqiUe5lyQWfpzErIgS0/tZ2ICBzrWDFn//siumIAydNBQy2qmRu9UkbkvC9YRtXi91v5EkMGOmonqqEDSxS/9xMUPtfp5JstQdE11UDHBye2olcRlCPoQSiL0ZHvfXPqqByA1g/CI7O3t0la6T6GiwPWLEAdx7r/JVbD0iaGbzF3eswVEq3+11BpGh3
  template:
    metadata:
      name: loki-s3-token
      namespace: loki
    type: Opaque
