apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis
resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: redis
    version: 24.1.2
    valuesFile: values.yaml
    namespace: redis
    includeCRDs: true

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: redis

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
