apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: redis-admin-credentials
  namespace: redis
spec:
  encryptedData:
    redis-password: AgAmrR37igz3AdfUARr/lQzAAJ6KdDLZoujSWW+fT4HwFIDEpbePl7UVML7l5OOpEsLDj3TtaZThXGF2UrRLcsnx47Yo4UhiIe6a5I87Qm1uKnQ9033O0i4LG+M1vfUQaIGPH/7QrndW4MV5Zt4Yen0Lju9jA5qxIfQphJJ+EK+o7C/Ud3cL/vkeNg/mOYk5L4/l/IzA7ditQDrLMk8mLTqjj0/CTCpNYSuvAyISeVjTwgBkBDw4JS0SakGU6JwmUU/34g75qFhEspgvZj8fPt8Zd2Lp2DNhFgTgmtS/KLrk1ZGPgV6/hlN+EMxgVhMMbIf2kBFwCx+DyymVbojgsMi3+MmmqyXXMzRXFFHC/KhnrBm+X41SVSHwBpH6NSvKT6BQZXOl+q8q5lHPjwTq7LlI5OnI53R4BI+hREmncMbNCK/mFezzOrPN2fWwRcR1otFiinBgBsm+M/5jGceEwJ5MG1BVGq7P6QYv/Km16JPGKUsFETkPwZBLzb9ZxrlRZdSmjdCA8xB5T31nHmeFI2ysIGHvVEUkjeMLc7JkXdZFug5DtPms7fsPAj2Ka72E2eioh/11S8oAz6WSeJ2995Ox+b+CYLtRzvRdl3hLmh0VyAEFQ2D2YLC4oSxmjdmBx9lUjErNiZUkgK7hJmpKMUVsMZjbtbUg9Pat4FCkLHuuSwIlGFmijDKwACABamY96HuF7iKs6Ft6FGe56DJkpBU3hgZxCQ==
  template:
    metadata:
      name: redis-admin-credentials
      namespace: redis
