---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./sealedsecret.yaml
  - ./clusterissuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    version: v1.19.2
    valuesFile: values.yaml
    includeCRDs: true
    namespace: cert-manager

patches:
  # https://github.com/cert-manager/cert-manager/pull/6192
  - patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
    target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager
