apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-operator
resources:
  - ./namespace.yaml

helmCharts:
  - name: grafana-operator
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: grafana-operator
    version: 5.21.4
    valuesFile: values.yaml
    namespace: grafana-operator
    includeCRDs: true

labels:
  - includeSelectors: false
    pairs:
      homelab.app: grafana-operator

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
