apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-operator
resources:
  - ./namespace.yaml

helmCharts:
  - name: grafana-operator
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: grafana-operator
    version: 5.21.4
    valuesFile: values.yaml
    includeCRDs: true
    namespace: grafana-operator
    valuesInline:
      watchNamespace: ""

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: grafana-operator

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"
