apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: alloy-ui-tls
  namespace: alloy
spec:
  secretName: alloy-ui-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - alloy.zimmermann.sh
