apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: alloy-ui
  namespace: alloy
  annotations:
    external-dns.alpha.kubernetes.io/target: alloy.zimmermann.sh
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`alloy.zimmermann.sh`)
      priority: 10
      services:
        - kind: Service
          name: alloy-alloy-metrics
          port: 12345
  tls:
    secretName: alloy-ui-tls
