apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy
resources:
  - ./namespace.yaml
  - ./certificate.yaml
  - ./ingress-route.yaml

helmCharts:
  - name: k8s-monitoring
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: alloy
    version: 3.8.0
    valuesFile: values.yaml
    namespace: alloy
    includeCRDs: true

patches:
  # Configure LoadBalancer with Cilium BGP advertisement
  - target:
      kind: Service
      name: alloy-alloy-metrics
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/labels/bgp.cilium.io~1ip-pool
        value: default
      - op: add
        path: /metadata/labels/bgp.cilium.io~1advertise-service
        value: default

labels:
  - includeSelectors: false
    pairs:
      homelab.app: alloy

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
