apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy
resources:
  - ./namespace.yaml
  - ./certificate.yaml
  - ./ingressroute.yaml

helmCharts:
  - name: k8s-monitoring
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: alloy
    version: 3.7.5
    valuesFile: values.yaml
    namespace: alloy
    includeCRDs: true

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: alloy

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
