apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy
resources:
  - ./namespace.yaml
  - ./certificate.yaml
  - ./ingress-route.yaml

helmCharts:
  - name: k8s-monitoring
    repo: oci://ghcr.io/grafana/helm-charts
    releaseName: alloy
    version: 3.8.1
    valuesFile: values.yaml
    namespace: alloy
    includeCRDs: true

labels:
  - includeSelectors: false
    pairs:
      homelab.app: alloy

commonAnnotations:
  argocd.argoproj.io/sync-wave: "8"
