apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
  # Inject domain name into the Certificate and IngressRoute
  - sourceValue: prometheus.zimmermann.phd
    targets:
      - select:
          kind: Certificate
          name: prometheus-tls-cert
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: prometheus
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1

patches:
  # Prometheus Operator: Deploy with standardized resources and GOMEMLIMIT
  - target:
      kind: Deployment
      name: prometheus-operator
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: kube-prometheus-stack

      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GOMEMLIMIT
          value: "120586240"

  # Prometheus instance: Configure resources and TSDB persistence
  - target:
      kind: Prometheus
      name: prometheus
    patch: |-
      - op: test
        path: /metadata/name
        value: prometheus
      - op: test
        path: /spec/retention
        value: 10d

      - op: add
        path: /spec/resources
        value:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
      - op: add
        path: /spec/containers
        value:
          - name: prometheus
            env:
              - name: GOMEMLIMIT
                value: "482344960"

      - op: add
        path: /spec/storage/volumeClaimTemplate/spec/resources
        value:
          requests:
            storage: 1Gi

      - op: replace
        path: /spec/retention
        value: 7d

  # Alertmanager: Configure resources and GOMEMLIMIT
  - target:
      kind: Alertmanager
      name: prometheus
    patch: |-
      - op: test
        path: /metadata/name
        value: prometheus

      - op: add
        path: /spec/resources
        value:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
      - op: add
        path: /spec/containers
        value:
          - name: alertmanager
            env:
              - name: GOMEMLIMIT
                value: "120586240"

      - op: add
        path: /spec/storage/volumeClaimTemplate/spec/resources
        value:
          requests:
            storage: 64Mi
