apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets-controller
resources:
  - ./namespace.yaml

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    releaseName: sealed-secrets
    version: 2.18.0
    valuesFile: values.yaml
    namespace: sealed-secrets-controller
    includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-4"
