apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets-controller
resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml

helmCharts:
  - name: sealed-secrets-chart
    repo: oci://ghcr.io/alexander-zimmermann/charts
    releaseName: sealed-secrets
    version: 2.17.9
    valuesFile: values.yaml
    namespace: sealed-secrets-controller
    includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-4"
