---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dhi-registry-secret
  namespace: sealed-secrets-controller
spec:
  encryptedData:
    .dockerconfigjson: AgADZAu6+ReaQ3/ghDFh9f17yyVaKLwCKTjsXBzHYQXn6dqL2ShHJD2TXjURzT0mRAO9qy4aSD32rj8xwzhqGe5WKW49Uk4K4ZEo1pe7VFW3GvVGwbab+IsWqsL1lPOHvazYavS544G2/B0db6T9z5t0X2TWa7CHBKrmpUIHVANn5ldnMjom3N4/CnoBFhaWBZxHGPTm+RHNQnC7tX/Oq5S4OeNUtLLvgCXgS7KMIAyAh4ej9YIExd/3BSboE7JaWOe8dTme6WuNa4H2aaakpGxiqm6HRncz1N06XlQKJ3xoXrYb+X6QEtZvwz2XpKt98xw6NmUpMJXh/irWKTwMNEGBTojcoYlMmpp/ktv9+2OvPLzEtpo8S1Gk0QC6Jl1HCVQhJvFfFSKDyroRpGYn7q8+k6I7zMu063Gwouxk0bKskJnxN28/YVXqS1nngvbaTVSwc8EC4bWCoPkRhxcvzN09mPgxpnR9aQG6AASewpLkjS8QWxO2KoDWERYsuhbzmtelNjO5CGz3g43RZgP2QOT7qhPDCzXQDX797vqe15cGceGw1sL6FsLBEkSVQCUxTOqv6ljyNUJXwvN2mmQkCRp9RYNvazdh1x/USRCl7V8kSZ/PUY8bFy6C8f/f1wVqA0QgSmVSyru2iwZFLSCljFiuTfJsNk/VWuW0/BFQdExHJDBVLz6/Ojom1j68J049XwbLUuKSlbxdSFNL3NKE3P7Y6LgSq1Zi2VqfQhNnFXVZM+oHBvZQ3TF9YTcpTl/fG+JXjCYZ0jrCboglZY0DSYW+aZbGaSsoCMMOvtmROf8A8P0xy/6unLEb5O3d6tMe7EBkc4gWhx80mTssRGyoZUpSNZF5ELVcvNJYcnRvdwwmAVRZ/iBAXc9qnkI6jU9VlemOK6KRxhkd
  template:
    metadata:
      name: dhi-registry-secret
      namespace: sealed-secrets-controller
    type: kubernetes.io/dockerconfigjson
