apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dhi-registry-secret
  namespace: sealed-secrets-controller
spec:
  encryptedData:
    .dockerconfigjson: AgC2xJa2vtfLL1zCVFK5y3XAkCBkKEW+kwW8MJKXNo/PHCnZUAo6Js0PYN62s+DO+xlcxVXFi7QHEvpwWmHvBuXmgzvJmnfNbfv1VNK1lIZg31K0K/fLbkY+GQI1eoq+vc3n0l1CrVwAwqqmW9NGC8LU1fot8uWnRXyAX+a34j7FVfbfOKTt+LCJbMKpXOKewOAhc/PQZF+xrB36Mk+XS+1756zbDqgQN1Hn1EBCoOxsZOSbTnJ/huVWl/pzkpWoitKdxhCyTGZNuvEHEQfVLA+r7aVRhL+yj2uwvvja0llX4YR92B+YKzzMUyaCNc771lhVPyzEWeml9Vch+hdVIj2ekU3Dy9qarQwgKwj4zYrtrbOihfF5YE0F+2phTIefjqGAq6sgxTDPByLihPBOA1S7SSmNVEy8YwoKGRDUW1bHqF+uSua/H+onqOM6RPn9kE3+0LxFid7r3W73ks67Qo5DKkVYz3yz0/OMRjKZ8iX+62Wc3oDGKWiuSHr3Va9zADnMy0I2wJQAQmzT0ARg3pDzwth4+ycOhLn4rEUtFrGMHlCaPU3wF5HemzpVy2HVlEF9DN1aZwRRf+yTtXIRJ0F/b7+hTYRcqJDhkPQEtAt9i6lC50hz2rBu2tXgIATTfJ4rJVt7QqqmLOezw+1VTIlXrf01iPbwWeOQpWjtr3mR1ya++t+J18A7DIK29+aeExAv4Qfx6iMa/7vNfERS7lKFstn7RiSxDGBVCt0JMw6+ATNrDLUqusnjeAPxq1UjXpe7b9wE0FtSLHUNRPBzt8HXORZVPdXpoBnslO4R6AA5kyG94V66kZh1580JXB1yD6f2gBGDC4AcUkReVkAf3obG0QF6ck6cjhV0A/Wd5UJ3iMplbpQvrMi7xvKz6Uv+DCPDpFaUz8xE
  template:
    metadata:
      name: dhi-registry-secret
      namespace: sealed-secrets-controller
    type: kubernetes.io/dockerconfigjson
