apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dhi-registry-secret
  namespace: sealed-secrets-controller
spec:
  encryptedData:
    .dockerconfigjson: AgAjJpxrn2ldPG8Rq6u9452/qTso8Atk6oYwhiClXPphKJOgxZIUgYChDX8bR9qaMoD6pNlL6Dtj/Kga3GvCHUz1A5T7EpeNjL3wMKeSUBnR5WnztW0ieKV32LyJwwo1DTxUZqY0nZmiO85ZlHIm7F74Uf2XAgFKt2eMXOe4uoTl/hlveTzac8eZqtVB5XomoVU0M/Ly2kNbOt+cEJOEnGrJfVIvtz0GiQkhp3atn+De3dP3gOZfueskgAp+gsS0FAvO7iZZ5uKTv1LtT1C5IxB9ElnVAmYF33sQzg+AGwD1acSsvEc9QfVFp/CaFsoIb/sRrs8LUGQCndt+DwbmYzdloInJ2Uwfvnm81a1IBcIy4q7nqyElnRYCEa3S5ASmGctJHgxpFgLHLFN9vUj1EaAjPZ5n2D7P6ai25Y4cqSYJ+ZKMCd/iFer28TCbcOzGFnBhjvuFjBCAzpSC5bMHTdilyvWbCDQjVNXmMRopqNv6IsEN2cCUzRJZq0cYDdeKLCXtWo7Z5UC4DPKkbkzUTalwSQ+WBeKYIkHnRAi5wdQsm7X8/3E6Rdy1oM1viCt12XMWoa+wAlhOYW+UbHPJWsRb8SZUlPVfnneHWVLymtHSk061W5F1pVAUTrgbgv13I+9pIFxeZDrjXc2VdCeGmGgQTOM2KwJQZFrXkSs8d9bZPLoe8r/+x17VeNemmMEPkH87Pgro4jFk4FHI7DTAn9VdaaRHBsGRKhSPByDaFruUOcXHMFnkyRIlm1yVAK+2g97qJx/JM0UhTJ4rNB7iZFflfzjaJ1sg0bXEqTgvogCJKgrzn5mRp6hkfD6M7uGfRU2SZHsILsb4gBlYRtB/lgGT9wm5f5/YUcUQWpje
  template:
    metadata:
      name: dhi-registry-secret
      namespace: sealed-secrets-controller
    type: kubernetes.io/dockerconfigjson
