apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: dhi-registry-secret
  namespace: sealed-secrets-controller
spec:
  encryptedData:
    .dockerconfigjson: AgCk5Tsl+1IKM9WbPP1gzwfZnvRTd58I+Yha4HgcR1VnqFhiRWwHnaFdTkzpez9snBv0NqICV5UY8o4Bu41rZiWvl38b4euU3eYUduG6lLK9zmJnPxFukHNf0/qeYgt2w31vWUFpp4OUwiHLYK6UhbnXHtCYD0UO0/w6Jy0ewY0lUOF8q67zronUZgrdqdAR1muhf8dmmr8OvH25MyC4bUD2GK/KDiM5dsw8ryBfOfHirn79LYSNzQ7aEU5hTwwIBnWGgoLCEC5gLoivZym5JfpTtnjPr+Gsaw53u8rJimM6da5e8iDmj9uC127m4t4IjYd0tt6il87ZNa+hHfX9q2cbFFfmV9UAt3VDZOJHvsV9tU/OnTEQ3nYjACZ4hKxLeIBF0p2K2tPdFgHcaanaRVdVYjD6f1VDf3/4wmmOyDe+TIvAK+RXlXpzzeN6zxiScXfdSCoj6hFOyZ9+94/PPJTwhUO2eADWvT+lHvBeNQHNmMIqDegXeSZaz7JKMkt0EYAQIrTU1g746qLJD9N4jQvqy1gcw3iaTWlkYobnIjysOriMudHDqagPui8lh90HsP+VQ9AuFHClS/IdQhXLMg0WZICY+M6Kz6cGodPOyl47BxbQ1BDPzHMatpBk1Rx27FROLZNI+UlSpW6sS+MASrOLHscosgVZqkQS6/vFb+6q06qfjFLryqxxbV7wRbZ+NpYbAM2yGmkdT8x1zHpayWdIkXTLgTNSPhuIVedTsVM6wvIUWPpaNhqA7yg3F+vGNWSQ5/FxyKK2l9/o1+ceprHJWMoUhMn2wA//xAwI0M9INFMdtyH70tSF5WHxP/MCFFuuOdV19Sars9bxNw/d68+vfU1Cbubn++g+55usT65A3rj0gB89CffO/rUXs6Odz7HKtLqL0y34
  template:
    metadata:
      name: dhi-registry-secret
      namespace: sealed-secrets-controller
    type: kubernetes.io/dockerconfigjson
