apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: cluster
  namespace: gitops-controller
spec:
  generators:
    - git:
        repoURL: https://github.com/alexander-zimmermann/homelab
        revision: HEAD
        # Scan Base Kustomization files
        files:
          - path: kubernetes/components/*/base/kustomization.yaml
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      # Segment 2 is component name (k8s-cluster/components/NAME/base/kustomization.yaml)
      name: "{{index .path.segments 2}}-prod"
      annotations:
        # Read sync-wave from the parsed Kustomization file content
        argocd.argoproj.io/sync-wave: '{{ index .commonAnnotations "argocd.argoproj.io/sync-wave" | default "0" }}'
        argocd.argoproj.io/compare-options: '{{ index .commonAnnotations "argocd.argoproj.io/compare-options" | default "" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/alexander-zimmermann/homelab
        targetRevision: HEAD
        # Construct path to overlays/prod
        path: kubernetes/components/{{index .path.segments 2}}/overlays/prod
      destination:
        server: https://kubernetes.default.svc
        # Read namespace from the parsed Kustomization file content
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
