apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: argocd-tls-cert
spec:
  secretName: argocd-tls-cert
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.zimmermann.sh
