apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: argocd-server
  namespace: gitops-controller
  annotations:
    external-dns.alpha.kubernetes.io/target: udm-pro.zimmermann.sh
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.zimmermann.sh`)
      priority: 10
      services:
        - kind: Service
          name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.zimmermann.sh`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - kind: Service
          name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-tls-cert
