apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-controller
resources:
  - ./certificate.yaml
  - ./ingressroute.yaml
  - ./sealedsecret.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
