apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-controller
resources:
  - ./certificate.yaml
  - ./ingress-route.yaml
  - ./sealed-secret.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
