apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: metrics-server-chart
    repo: oci://ghcr.io/alexander-zimmermann/charts
    releaseName: metrics-server
    version: 3.13.0
    valuesFile: values.yaml
    namespace: kube-system
    includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"
