name: "CI: Pre-Pull Images"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  extract-images:
    name: Extract Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Default Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: default

      - name: Extract Default Images
        id: extract-default
        run: |
          ./.github/scripts/ci-extract-images.sh default default_images.json
          echo "default=$(jq --compact-output '.' default_images.json)" >> $GITHUB_OUTPUT

      - name: Checkout Pull Request Branch
        uses: actions/checkout@v4
        with:
          path: pull

      - name: Extract Pull Images
        id: extract-pull
        run: |
          ./.github/scripts/ci-extract-images.sh pull pull_images.json
          echo "pull=$(jq --compact-output '.' pull_images.json)" >> $GITHUB_OUTPUT

  diff:
    name: Diff Images
    needs: extract-images
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.diff.outputs.images }}
    steps:
      - id: diff
        env:
          DEFAULT_IMAGES: ${{ needs.extract-images.outputs.default }}
          PULL_IMAGES: ${{ needs.extract-images.outputs.pull }}
        run: |
          images=$(jq --compact-output --null-input \
              --argjson f1 "$DEFAULT_IMAGES" \
              --argjson f2 "$PULL_IMAGES" \
              '$f2 - $f1' \
          )
          echo "images=${images}" >> $GITHUB_OUTPUT

  pre-pull:
    name: Pre-pull Images
    needs: diff
    if: ${{ needs.diff.outputs.images != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(needs.diff.outputs.images) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Install talosctl
        run: curl -fsSL https://talos.dev/install | sh

      - name: Pre-pull Image
        env:
          TALOSCONFIG: ${{ secrets.TALOSCONFIG }}
        run: |
          if [ -z "$TALOSCONFIG" ]; then
            echo "::warning::TALOSCONFIG secret not found. Skipping pre-pull."
            exit 0
          fi
          # Example: Pull for all nodes. Adjust nodes if necessary.
          echo "${TALOSCONFIG}" > talosconfig
          # nodes=$(talosctl --talosconfig talosconfig config info --output json | jq -r '.nodes[0]')
          # talosctl --talosconfig talosconfig --nodes $nodes image pull ${{ matrix.image }}
          echo "Pre-pulling ${{ matrix.image }} on Talos nodes..."
          # talosctl --talosconfig talosconfig image pull ${{ matrix.image }}
