apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Ingress host
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`argocd.zimmermann.phd`)
      - op: replace
        path: /spec/routes/1/match
        value: Host(`argocd.zimmermann.phd`) && Header(`Content-Type`, `application/grpc`)
    target:
      kind: IngressRoute
      name: argocd-server

  # Certificate DNS names
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: argocd.zimmermann.phd
    target:
      kind: Certificate
      name: argocd-tls-cert

  # Scale down replicas - Server
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: argocd-server

  # Scale down replicas - Repo Server
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: argocd-repo-server
