apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../../bootstrap/gitops-controller/overlays/dev/

patches:
  # Ingress host
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`argocd.zimmermann.phd`)
      - op: replace
        path: /spec/routes/1/match
        value: Host(`argocd.zimmermann.phd`) && Header(`Content-Type`, `application/grpc`)
    target:
      kind: IngressRoute
      name: argocd-server

  # Certificate DNS names
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: argocd.zimmermann.phd
    target:
      kind: Certificate
      name: argocd-tls-cert
