---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: IngressRoute
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`argocd.zimmermann.phd`)
      - op: replace
        path: /spec/routes/1/match
        value: Host(`argocd.zimmermann.phd`) && Header(`Content-Type`, `application/grpc`)

  - target:
      kind: Certificate
      name: argocd-tls-cert
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: argocd.zimmermann.phd
